// middleware.js
// Markdown negotiation for AI agents (WebForge V5): when a client's Accept header genuinely prefers text/markdown over
// text/html, serve the markdown twin generated by scripts/gen-markdown.mjs. Every other request is untouched.
import { NextResponse } from 'next/server';

export const config = { matcher: ['/((?!_next/|api/|md/|admin|order/|checkout|thank-you|.*\\..*).*)'] };

// Parse q-values: a browser or crawler that sends "text/html, text/markdown;q=0.9" prefers HTML and must keep getting the full page.
function prefersMarkdownOverHtml(accept) {
  let mdQ = -1;
  let htmlQ = -1;
  for (const part of accept.split(',')) {
    const [type, ...params] = part.trim().split(';').map((s) => s.trim());
    let q = 1;
    for (const p of params) { const m = /^q=([\d.]+)$/.exec(p); if (m) q = parseFloat(m[1]); }
    if (type === 'text/markdown') mdQ = Math.max(mdQ, q);
    if (type === 'text/html') htmlQ = Math.max(htmlQ, q);
  }
  return mdQ > -1 && mdQ > htmlQ;
}

export async function middleware(request) {
  const accept = request.headers.get('accept') || '';
  if (!accept.includes('markdown') || !prefersMarkdownOverHtml(accept)) return NextResponse.next();
  const { pathname } = request.nextUrl;
  const dir = pathname.endsWith('/') ? pathname : `${pathname}/`;
  const res = await fetch(new URL(`/md${dir}index.md`, request.url));
  if (!res.ok) return NextResponse.next();
  const body = await res.text();
  return new NextResponse(body, {
    headers: {
      'Content-Type': 'text/markdown; charset=utf-8',
      Vary: 'Accept',
      'Cache-Control': 'public, max-age=0, must-revalidate',
      'X-Markdown-Tokens': String(Math.ceil(body.length / 4)),
    },
  });
}
