// src/config/brands.js
// Australian Golf Buggy Brands (WebForge v9.1 AU)
// Section 5 Brand Directory — 27 Brands with Blurbs, Origin, Spare Parts & Full Lineup

export const BRANDS = [
  {
    slug: 'mgi',
    name: 'MGI',
    country: 'Australia',
    blurb: 'Australia\'s number one electric golf buggy brand.',
    origin: 'Australian engineered & owned',
    logo: 'MGI Golf Australia',
    h1: 'MGI Golf Buggies & Spare Parts Australia',
    pageTitle: 'MGI Golf Buggies Australia | Zip Navigator, Ai & Parts',
    metaDescription: 'Shop MGI electric golf buggies in Australia. MGI Zip Navigator AT, Zip X1, X3, X5 and MGI Ai Series with lithium batteries and local Australian service.',
    introCopy: 'MGI is Australia\'s premier manufacturer of motorised and remote-control golf buggies, renowned for the Zip Navigator AT and Ai follow series. Engineered in Australia for local turf and terrain with comprehensive factory service backup.',
    popularModels: ['MGI Zip Navigator AT', 'MGI Ai Navigator GPS+', 'MGI Ai Navigator Halo', 'MGI Zip X5', 'MGI Zip X3', 'MGI Zip X1'],
    partsCategories: ['24V & 12V Lithium Batteries', 'Smart Chargers', 'Front & Rear Wheel Assemblies', 'Motor Controllers & Axles', 'Umbrella & GPS Holders']
  },
  {
    slug: 'motocaddy',
    name: 'Motocaddy',
    country: 'UK',
    blurb: 'The world\'s number one electric golf trolley brand.',
    origin: 'Compact folding pioneer',
    logo: 'Motocaddy',
    h1: 'Motocaddy Electric Golf Buggies & Parts Australia',
    pageTitle: 'Motocaddy Golf Buggies Australia | M7 Remote & M5 GPS',
    metaDescription: 'Motocaddy electric golf buggies with ultra-compact M-Series folding, responsive remote controls, touchscreen GPS and high-capacity lithium power.',
    introCopy: 'Motocaddy builds world-class compact-folding electric golf buggies featuring touchscreen GPS distances, whisper-quiet 28V drive systems, and downhill speed control.',
    popularModels: ['Motocaddy M7 GPS Remote', 'Motocaddy M7 Remote', 'Motocaddy M5 GPS DHC', 'Motocaddy M1 DHC'],
    partsCategories: ['28V Lithium Battery Packs', 'High-Speed Chargers', 'DHC Wheel Kits', 'Accessory Stations', 'Travel Covers']
  },
  {
    slug: 'powakaddy',
    name: 'PowaKaddy',
    country: 'UK',
    blurb: 'British electric trolleys with GPS and electronic braking.',
    origin: 'Electric trolley heritage since 1983',
    logo: 'PowaKaddy',
    h1: 'PowaKaddy Electric Golf Buggies & Parts Australia',
    pageTitle: 'PowaKaddy Golf Buggies Australia | RX1 GPS & FX7',
    metaDescription: 'Explore PowaKaddy electric golf buggies with Plug \'n\' Play lithium batteries, 1-Click folding and widescreen GPS course mapping.',
    introCopy: 'PowaKaddy combines heritage golf trolley craftsmanship with modern Plug \'n\' Play ultra-thin lithium technology and high-definition colour touchscreens.',
    popularModels: ['PowaKaddy RX1 GPS Remote', 'PowaKaddy FX7 GPS', 'PowaKaddy CT', 'PowaKaddy DLX'],
    partsCategories: ['Plug \'n\' Play Lithium Batteries', 'Winter Wheels', 'Electronic Braking Spares', 'Seats & Scorecard Holders']
  },
  {
    slug: 'stinger-golf',
    name: 'Stinger Golf',
    country: 'Australia',
    blurb: 'Australian designed and made remote-control buggies.',
    origin: 'Australian designed & manufactured',
    logo: 'Stinger Golf',
    h1: 'Stinger Golf Buggies & Spare Parts Australia',
    pageTitle: 'Stinger Golf Buggies Australia | SG-4 Crossover & Parts',
    metaDescription: 'Australian designed Stinger SG-4 Crossover remote-control buggies with wide rear track stability and comprehensive local spare parts.',
    introCopy: 'Stinger Golf is an Australian brand engineered specifically for local undulating fairways, featuring wide-track stability, direct-drive powertrains, and all-inclusive accessory packages.',
    popularModels: ['Stinger SG-4 Crossover Remote', 'Stinger SG-4 Push Buggy'],
    partsCategories: ['Stinger SG-4 Rear Wheels', 'Drive Motors', 'Lithium Packs', 'Cup & Umbrella Holders']
  },
  {
    slug: 'alphard',
    name: 'Alphard Golf',
    country: 'USA',
    blurb: 'The Club Booster conversion kit and Cybercart remote buggy.',
    origin: 'Electric conversion pioneer',
    logo: 'Alphard Golf',
    h1: 'Alphard Golf Buggies & Club Booster Conversion Kits',
    pageTitle: 'Alphard Club Booster V2Pro & Cybercart Australia',
    metaDescription: 'Convert your manual push buggy into a remote electric buggy with Alphard Club Booster V2Pro. Also featuring the Cybercart follow buggy.',
    introCopy: 'Alphard Golf revolutionised manual buggies with the Club Booster V2Pro, allowing golfers to convert standard push buggies into dual-motor remote buggies in seconds.',
    popularModels: ['Alphard Club Booster V2Pro', 'Alphard Cybercart Follow Buggy'],
    partsCategories: ['Clicgear & Rovic Brackets', 'TFS Follow Sensors', 'Wheelie Bars', 'Replacement Remotes']
  },
  {
    slug: 'stewart-golf',
    name: 'Stewart Golf',
    country: 'UK',
    blurb: 'Premium British follow and remote buggies.',
    origin: 'Hand-built British engineering',
    logo: 'Stewart Golf',
    h1: 'Stewart Golf Follow & Remote Buggies Australia',
    pageTitle: 'Stewart Golf Buggies Australia | Q Follow & X10 Follow',
    metaDescription: 'Stewart Golf premium follow buggies with Bluetooth Seventh-Generation Follow technology, microcellular composite chassis and carbon finishes.',
    introCopy: 'Stewart Golf produces the world\'s most sophisticated autonomous follow golf buggies, handcrafted in Great Britain with bespoke electronics and whisper-quiet drivetrains.',
    popularModels: ['Stewart Q Follow', 'Stewart X10 Follow'],
    partsCategories: ['SmartPower Lithium Batteries', 'Handsets & Follow Sensors', 'Rear Stabiliser Wheels', 'Insulated Drink Flasks']
  },
  {
    slug: 'clicgear',
    name: 'Clicgear',
    country: 'Singapore',
    blurb: 'The benchmark push buggy, plus the Rovic sub-range.',
    origin: 'Aircraft-grade aluminium push buggies',
    logo: 'Clicgear',
    h1: 'Clicgear 3-Wheel & 4-Wheel Push Buggies & Parts',
    pageTitle: 'Clicgear Golf Buggies Australia | Model 4.5 & Rovic',
    metaDescription: 'Buy Clicgear Model 4.5, Rovic RV1S and Swivel 2.0 push golf buggies in Australia. Heavy-duty aircraft-grade frames, compact fold and rich accessory ecosystem.',
    introCopy: 'Clicgear set the international benchmark for rugged 3-wheel manual push buggies. Featuring heavy-gauge aircraft-grade aluminium tubing and positive-lock brakes.',
    popularModels: ['Clicgear Model 4.5', 'Clicgear Rovic RV1S', 'Clicgear Rovic Swivel 2.0'],
    partsCategories: ['Clicgear Wheel Kits', 'Secondary Struts', 'Brake Cables & Levers', 'Hedgehog Winter Wheels', 'Umbrella Adjusters']
  },
  {
    slug: 'big-max',
    name: 'Big Max',
    country: 'Germany',
    blurb: 'Premium German push buggies including the flat-fold Blade.',
    origin: 'German engineering & ultra-flat fold',
    logo: 'Big Max',
    h1: 'Big Max Push Golf Buggies & Accessories Australia',
    pageTitle: 'Big Max Golf Buggies Australia | Blade IP 2 & IQ 2',
    metaDescription: 'Big Max ultra-flat folding push golf buggies. Fold down to just 12.5cm for effortless car boot packing with robust 5-year warranties.',
    introCopy: 'Big Max produces the world\'s flattest folding push buggies, such as the Blade IP 2 and IQ 2 360, delivering European build precision and zero-effort folding.',
    popularModels: ['Big Max Blade IP 2', 'Big Max IQ 2', 'Big Max IQ 2 360'],
    partsCategories: ['Swivel Wheel Assemblies', 'Scorecard Consoles', 'Wheel Covers', 'Quick-Lok Bases']
  },
  {
    slug: 'qod-golf',
    name: 'QOD Golf',
    country: 'Australia',
    blurb: 'Australian made compact push buggy, upgradeable to electric.',
    origin: 'Australian made compact design',
    logo: 'QOD Golf',
    h1: 'QOD Golf Compact Buggies Australia',
    pageTitle: 'QOD Golf Buggies Australia | Modular Push to Electric',
    metaDescription: 'Australian designed and made QOD Compact golf buggies. The smallest folding full-size buggy in the world, upgradeable to electric and remote.',
    introCopy: 'QOD Golf is an Australian innovation holding international design awards for the world\'s most compact folding full-size golf buggy, with modular upgrade paths.',
    popularModels: ['QOD Compact Buggy', 'QOD Electric Modular Kit'],
    partsCategories: ['Replacement Wheels', 'Modular Drive Packs', 'Carry Bags', 'Umbrella Mounts']
  },
  {
    slug: 'brosnan',
    name: 'Brosnan',
    country: 'Australia',
    blurb: 'Value-premium push buggies familiar to Australian club golfers.',
    origin: 'Australian club golf heritage',
    logo: 'Brosnan Golf',
    h1: 'Brosnan Golf Buggies & Accessories Australia',
    pageTitle: 'Brosnan Golf Buggies Australia | Zodiac 3 & Parts',
    metaDescription: 'Brosnan 3-wheel and 4-wheel push buggies with adjustable handles, scorecard consoles and reliable Australian club warranty.',
    introCopy: 'Brosnan Golf has been a household name across Australian club fairways for decades, delivering durable, practical 3-wheel push buggies at exceptional value.',
    popularModels: ['Brosnan Zodiac 3', 'Brosnan Compact 4-Wheel'],
    partsCategories: ['Front Swivel Wheels', 'Scorecard Consoles', 'Brake Assemblies', 'Storage Nets']
  },
  {
    slug: 'ecar',
    name: 'ECAR',
    country: 'China (AU distributed)',
    blurb: 'Best-value new lithium ride-on golf carts.',
    origin: 'Automotive lithium golf carts & commercial utility',
    logo: 'ECAR Commercial Carts',
    h1: 'ECAR Electric Golf Carts & Utility Buggies Australia',
    pageTitle: 'ECAR Golf Carts for Sale Australia | Lithium A2, A4 & Magnum',
    metaDescription: 'ECAR 2-seat, 4-seat, 6-seat and lifted golf carts with automotive-grade lithium batteries, hydraulic disc brakes and direct Australian warranty.',
    introCopy: 'ECAR is Australia\'s leading supplier of new lithium golf course carts, luxury estate buggies, and commercial utility vehicles, powered by premium AC brushless motors.',
    popularModels: ['ECAR Lithium A2', 'ECAR Lithium A4', 'ECAR Compass 4S LFT', 'ECAR Compass 6S LFT', 'ECAR Lithium Magnum 4S', 'ECAR Lithium A2 Utility'],
    partsCategories: ['LiFePO4 Lithium Battery Packs', 'High-Output AC Motor Controllers', 'Lifted Suspension Kits', 'All-Terrain Turf Tyres', 'Windshields & Enclosures']
  },
  {
    slug: 'tomberlin',
    name: 'Tomberlin',
    country: 'USA',
    blurb: 'American lifted and street-styled premium carts.',
    origin: 'Street-legal luxury LSV',
    logo: 'Tomberlin Automotive',
    h1: 'Tomberlin Luxury Electric Golf Carts Australia',
    pageTitle: 'Tomberlin Golf Carts Australia | E-Merge Defender & Ghosthawk',
    metaDescription: 'Tomberlin luxury electric street-legal golf carts. 4-wheel hydraulic disc brakes, 3-point seatbelts, illuminated headliners and digital dash.',
    introCopy: 'Tomberlin manufactures the gold standard in street-legal Low-Speed Vehicles (LSV) and luxury resort carts, equipped with automotive safety glass and digital telemetry.',
    popularModels: ['Tomberlin E-Merge Defender 4 Seat', 'Tomberlin E-Merge Ghosthawk 4 Seat', 'Tomberlin E-Merge Beachcomber 6 Seat', 'Tomberlin E-Merge SS 4 Seat', 'Tomberlin E-Merge Revenge 4 Seat'],
    partsCategories: ['Hydraulic Disc Brake Calipers', 'Custom Wheels & Tyres', 'Digital Displays', 'Soundbars & Lighting']
  },
  {
    slug: 'club-car',
    name: 'Club Car',
    country: 'USA',
    blurb: 'The industry-standard OEM golf car.',
    origin: 'Rustproof AlumiCore aircraft aluminium',
    logo: 'Club Car',
    h1: 'Club Car Golf Carts for Sale Australia',
    pageTitle: 'Club Car Golf Carts Australia | Onward, Tempo & Precedent',
    metaDescription: 'New and certified ex-fleet Club Car electric golf carts. Onward 2-seat, 4-seat lifted and Carryall utility vehicles with AlumiCore frames.',
    introCopy: 'Club Car is celebrated globally for its rustproof AlumiCore aircraft-grade aluminium chassis, whisper-quiet performance, and enduring resale value across Australian courses.',
    popularModels: ['Club Car Onward 2-Seat', 'Club Car Tempo Lithium', 'Club Car Precedent (Ex-Fleet)'],
    partsCategories: ['Trojan 48V Battery Sets', 'Lithium Drop-in Conversion Kits', 'OEM Solenoids & Controllers', 'Windshields & Bag Covers']
  },
  {
    slug: 'yamaha',
    name: 'Yamaha',
    country: 'Japan',
    blurb: 'OEM golf cars and side-by-side UTVs.',
    origin: 'Automotive Japanese reliability',
    logo: 'Yamaha Golf-Car',
    h1: 'Yamaha Golf Carts & Side-by-Side UTVs Australia',
    pageTitle: 'Yamaha Golf Carts & SxS Australia | Drive2, Wolverine & RMAX',
    metaDescription: 'Yamaha Drive2 AC electric golf carts, Wolverine X2, YXZ1000R and RMAX 1000 side-by-sides with legendary Japanese reliability.',
    introCopy: 'Yamaha Golf-Car and Powersports delivers unmatched Japanese reliability, independent rear suspension, and class-leading recreational and farm side-by-sides.',
    popularModels: ['Yamaha Drive2 Lithium / Petrol', 'Yamaha Drive / G29 (Used)', 'Yamaha Wolverine X2 850', 'Yamaha RMAX2 1000', 'Yamaha YXZ1000R SS XT-R'],
    partsCategories: ['Yamaha Clutch Belts & Bushings', 'OEM Brake Drums & Shoes', 'Turf & Off-Road Tyres', 'Heavy-Duty Springs']
  },
  {
    slug: 'ez-go',
    name: 'E-Z-GO',
    country: 'USA',
    blurb: 'OEM golf cars, strong ex-fleet supply.',
    origin: 'Textron fleet reliability',
    logo: 'E-Z-GO Golf Carts',
    h1: 'E-Z-GO Golf Carts for Sale Australia',
    pageTitle: 'E-Z-GO Golf Carts Australia | RXV & TXT Reconditioned',
    metaDescription: 'Reconditioned ex-fleet and private E-Z-GO RXV electric golf carts. Automatic parking brakes, AC motor efficiency and lithium conversion options.',
    introCopy: 'E-Z-GO by Textron is one of the world\'s most widespread fleet golf carts, famous for the IntelliBrake automatic electronic parking brake on the RXV platform.',
    popularModels: ['E-Z-GO RXV (Ex-Fleet Reconditioned)', 'E-Z-GO Express 4-Seat'],
    partsCategories: ['48V RXV Motor Controllers', 'IntelliBrake Assemblies', 'Trojan T105 Battery Sets', 'Lithium Swap Kits']
  },
  {
    slug: 'evolution',
    name: 'Evolution',
    country: 'USA (AU distributed)',
    blurb: 'Modern touchscreen lithium carts.',
    origin: 'Touchscreen luxury electric carts',
    logo: 'Evolution Electric Vehicles',
    h1: 'Evolution Electric Golf Carts Australia',
    pageTitle: 'Evolution Golf Carts Australia | D5 4-Seat Lithium',
    metaDescription: 'Evolution D5 luxury 4-seat electric golf carts with automotive touchscreens, Bluetooth sound systems and maintenance-free lithium batteries.',
    introCopy: 'Evolution Electric Vehicles brings automotive-grade interiors to golf carts, featuring multi-functional digital touchscreens, backup cameras, and luxury seating.',
    popularModels: ['Evolution D5 4-Seat Touchscreen'],
    partsCategories: ['Touchscreen Dash Modules', 'Soundbar Assemblies', 'Lithium Chargers', 'Custom 14" Alloy Wheels']
  },
  {
    slug: 'tara',
    name: 'Tara',
    country: 'China (AU distributed)',
    blurb: 'AU-imported lithium carts, modern styling.',
    origin: 'Aluminium chassis modern lithium carts',
    logo: 'Tara Golf Carts',
    h1: 'Tara Electric Golf Carts Australia',
    pageTitle: 'Tara Golf Carts Australia | Spirit Plus & Roadster 2+2',
    metaDescription: 'Tara Spirit Plus, Spirit Pro and Roadster 2+2 electric golf carts with aluminium frames, lithium batteries and modern styling.',
    introCopy: 'Tara manufactures modern electric golf carts and personal transport vehicles with lightweight aluminium chassis, smart touchscreens, and efficient lithium drivetrains.',
    popularModels: ['Tara Spirit Plus 2-Seat', 'Tara Spirit Pro 2-Seat', 'Tara Roadster 2+2'],
    partsCategories: ['Alloy Wheels & Tyres', 'LED Lighting Kits', 'Lithium Packs', 'Custom Enclosures']
  },
  {
    slug: 'garia',
    name: 'Garia',
    country: 'Denmark',
    blurb: 'Danish luxury and street-legal golf cars.',
    origin: 'Hand-crafted Danish supercar luxury',
    logo: 'Garia Luxury Cars',
    h1: 'Garia Luxury Golf Cars & Street Legal LSV Australia',
    pageTitle: 'Garia Luxury Golf Cars Australia | Danish Handcrafted',
    metaDescription: 'Handcrafted Danish bespoke golf cars featuring carbon fibre bodywork, built-in refrigerators, Mansory styling and street-legal registration options.',
    introCopy: 'Garia creates the world\'s most exclusive bespoke luxury golf cars, handcrafted in Denmark alongside supercars with built-in champagne chillers and genuine Italian leather.',
    popularModels: ['Garia Golf Lithium', 'Garia Street Legal 2+2'],
    partsCategories: ['Bespoke Interior Accents', 'Refrigerator Units', 'Mansory Styling Parts', 'Custom Luxury Wheels']
  },
  {
    slug: 'can-am',
    name: 'Can-Am',
    country: 'Canada',
    blurb: 'Premium recreational and utility side-by-sides.',
    origin: 'Rotax-powered off-road performance',
    logo: 'Can-Am Off-Road',
    h1: 'Can-Am Side-by-Side UTVs & Buggies Australia',
    pageTitle: 'Can-Am Buggies Australia | Maverick & Defender UTV',
    metaDescription: 'Can-Am Maverick sport buggies and Can-Am Defender heavy-duty utility side-by-sides with Rotax power and class-leading tow ratings.',
    introCopy: 'Can-Am by BRP builds high-output off-road machines, from the desert-conquering Maverick turbo buggies to the heavy-duty Defender station workhorses.',
    popularModels: ['Can-Am Maverick Sport', 'Can-Am Defender Limited HD11', 'Can-Am Defender HD7'],
    partsCategories: ['Drive Belts & Clutches', 'Suspension Arms & Shocks', 'Heavy-Duty Winches', 'Windshields & Doors']
  },
  {
    slug: 'polaris',
    name: 'Polaris',
    country: 'USA',
    blurb: 'Ranger, RZR and XPEDITION side-by-sides.',
    origin: 'Global leader in off-road powersports',
    logo: 'Polaris Off-Road',
    h1: 'Polaris Ranger & RZR Off-Road Buggies Australia',
    pageTitle: 'Polaris Off-Road Buggies Australia | Ranger UTV & RZR',
    metaDescription: 'Polaris commercial and recreational off-road buggies in Australia. Ranger electric & petrol UTVs, RZR dune machines and NorthStar climate cabs.',
    introCopy: 'Polaris represents the benchmark in heavy-duty agricultural side-by-sides and dune buggies, providing on-demand true all-wheel drive and climate-controlled cabs.',
    popularModels: ['Polaris Ranger XP 1000 NorthStar', 'Polaris RZR Pro', 'Polaris Ranger 500'],
    partsCategories: ['Polaris On-Demand Drive Belts', 'Oil Filters & Service Kits', 'Heavy Duty Axles', 'Lock & Ride Cargo Accessories']
  },
  {
    slug: 'cfmoto',
    name: 'CFMOTO',
    country: 'China',
    blurb: 'Value-premium side-by-side UTVs.',
    origin: 'Feature-loaded utility vehicles',
    logo: 'CFMOTO Off-Road',
    h1: 'CFMOTO UTVs & Utility Buggies Australia',
    pageTitle: 'CFMOTO UTV Buggies Australia | UForce U10 Pro & EV',
    metaDescription: 'CFMOTO UForce side-by-side UTVs and electric farm buggies. High towing capacities, 3-seat benches, tipper trays and aggressive value.',
    introCopy: 'CFMOTO delivers exceptional value in work and recreational side-by-sides, equipped with standard power steering, winches, and tow hitches that undercut legacy rivals.',
    popularModels: ['CFMOTO UForce U10 Pro', 'CFMOTO UForce U6 EV Electric'],
    partsCategories: ['Service Filter Kits', 'CVT Belts', 'Hydraulic Tipper Rams', 'All-Terrain Wheel Packages']
  },
  {
    slug: 'kayo',
    name: 'Kayo',
    country: 'China (AU distributed)',
    blurb: 'Petrol dune buggies and entry UTVs.',
    origin: 'Dedicated recreational buggies',
    logo: 'Kayo Buggies',
    h1: 'Kayo Off-Road Dune Buggies & Side-by-Sides Australia',
    pageTitle: 'Kayo Dune Buggies Australia | S150 & S350 SxS',
    metaDescription: 'Kayo S150 and S350 petrol 2-seat dune buggies and recreational side-by-sides with CVT automatic transmissions and roll cages.',
    introCopy: 'Kayo builds accessible, reliable petrol-powered off-road buggies and side-by-sides with full steel roll cages, safety harnesses, and automatic transmissions.',
    popularModels: ['Kayo S150 2-Seat Buggy', 'Kayo S350 2-Seat UTV'],
    partsCategories: ['CVT Belts & Clutches', 'Brake Pads & Discs', 'Carburettor & EFI Spares', 'Throttle Cables']
  },
  {
    slug: 'crossfire',
    name: 'Crossfire',
    country: 'Australia',
    blurb: 'Australian off-road buggy and UTV brand.',
    origin: 'Australian owned all-terrain brand',
    logo: 'Crossfire Motorcycles & Buggies',
    h1: 'Crossfire Off-Road Buggies & Farm UTVs Australia',
    pageTitle: 'Crossfire Buggies Australia | Blazer 200R, 400GT & E5',
    metaDescription: 'Crossfire Australian designed petrol and electric off-road buggies, teenage dune buggies and silent 4WD farm UTVs.',
    introCopy: 'Crossfire is an Australian brand engineered to endure tough local tracks, offering everything from youth Blazer dune buggies to the silent Crossfire E5 4WD electric farm UTV.',
    popularModels: ['Crossfire Blazer 200R', 'Crossfire 400GT UTV', 'Crossfire E5 Electric Farm UTV'],
    partsCategories: ['Drive Chains & Sprockets', 'Brake Master Cylinders', 'Ignition Coils', 'Farm Utility Accessories']
  },
  {
    slug: 'gmx',
    name: 'GMX',
    country: 'China (AU distributed)',
    blurb: 'Entry petrol dune buggies.',
    origin: 'Recreational sand and trail buggies',
    logo: 'GMX Buggies',
    h1: 'GMX Off-Road Dune Buggies Australia',
    pageTitle: 'GMX Dune Buggies Australia | GKT110 & GKT150',
    metaDescription: 'GMX 110cc and 150cc petrol 2-seat dune buggies with roll cages, electric start and adjustable driver seats for property and beach use.',
    introCopy: 'GMX manufactures affordable, fun petrol dune buggies popular for Australian rural properties and recreational beach tracks.',
    popularModels: ['GMX GKT110 Dune Buggy', 'GMX GKT150 Dune Buggy'],
    partsCategories: ['Electric Starters & Solenoids', 'Brake Callipers & Pads', 'Tyres & Wheels', 'Centrifugal Clutches']
  },
  {
    slug: 'hammerhead',
    name: 'Hammerhead',
    country: 'USA',
    blurb: 'Kids and teen off-road buggies.',
    origin: 'Youth off-road buggy specialist',
    logo: 'Hammerhead Off-Road',
    h1: 'Hammerhead Kids & Teen Off-Road Buggies Australia',
    pageTitle: 'Hammerhead Buggies Australia | Torpedo 208cc',
    metaDescription: 'Hammerhead Torpedo youth off-road buggies with parent speed limiters, dual disc brakes and robust roll cage frames.',
    introCopy: 'Hammerhead Off-Road is an international specialist in youth and teen recreational go-karts and buggies, engineered with robust safety cages and speed governors.',
    popularModels: ['Hammerhead Torpedo 208cc'],
    partsCategories: ['Drive Belts & Clutches', 'Safety Harnesses', 'Brake Cables & Discs', 'Steering Rods']
  },
  {
    slug: 'thomson',
    name: 'THOMSON',
    country: 'China (AU distributed)',
    blurb: 'Value electric buggies (parts and accessories only).',
    origin: 'Electric golf buggy spares & support',
    logo: 'THOMSON Golf Buggy Parts',
    h1: 'THOMSON Golf Buggy Spare Parts & Batteries Australia',
    pageTitle: 'THOMSON Buggy Spares Australia | Batteries & Motors',
    metaDescription: 'Replacement lithium batteries, chargers, motors and wheels for THOMSON electric golf buggies in Australia.',
    introCopy: 'We provide comprehensive spare parts, replacement lithium battery upgrades, and technical service support for THOMSON electric golf buggies across Australia.',
    popularModels: ['THOMSON Electric Buggy Spares', 'THOMSON Lithium Battery Upgrade'],
    partsCategories: ['24V Lithium Replacement Packs', 'Smart Chargers', 'Axle Assemblies', 'Potentiometers & Speed Dials']
  },
  {
    slug: 'triumph',
    name: 'Triumph',
    country: 'Australia (retail brand)',
    blurb: 'Value push buggy spare parts and accessories.',
    origin: 'Australian retail golf buggy parts',
    logo: 'Triumph Golf Parts',
    h1: 'Triumph Golf Buggy Spare Parts & Accessories Australia',
    pageTitle: 'Triumph Golf Buggy Spares Australia | Wheels & Mounts',
    metaDescription: 'Replacement wheels, brake straps, consoles and umbrella mounts for Triumph manual golf push buggies.',
    introCopy: 'Keep your Triumph golf push buggy rolling with genuine fitment replacement wheels, foam tyres, umbrella brackets, and brake components.',
    popularModels: ['Triumph 3-Wheel Push Buggy Spares', 'Triumph Universal Accessories'],
    partsCategories: ['Replacement Wheels', 'Umbrella Holders', 'Brake Straps', 'Scorecard Consoles']
  }
];

export function getBrandBySlug(slug) {
  if (!slug) return null;
  const clean = slug.toLowerCase().trim();
  return BRANDS.find(b => b.slug === clean);
}

export function getAllBrands() {
  return BRANDS;
}
