// src/config/faq.js
// FAQ bank for The Buggy Shop. Single source for the homepage, /faq/, category pages and blog posts.
// Prices, speeds and ranges are COMPUTED from the product data below, so an answer can never drift from the shop.
// Rules (keyword engine): answers 40-55 words on the homepage, 40-65 elsewhere, concrete (never "it depends"), one link each.
// Road-rule answers are written cautiously: have them reviewed before changing them.
import { PRODUCTS } from './products.js';

const money = (n) => '$' + Math.round(n).toLocaleString('en-AU');
const range = (f) => { const l = PRODUCTS.filter(f).map((p) => p.price); return { min: Math.min(...l), max: Math.max(...l) }; };
const nums = (a) => a.filter((x) => Number.isFinite(x));
const carts = PRODUCTS.filter((p) => p.category === 'luxury-golf-carts' && p.subcategory !== 'used');
const speeds = nums(carts.map((p) => parseInt(String(p.specs?.topSpeed || '').match(/(\d+)\s*km/)?.[1], 10)));
const ranges = nums(carts.map((p) => parseInt(String(p.specs?.range || '').match(/(\d+)/)?.[1], 10)));
const pr = (frag) => { const p = PRODUCTS.find((x) => x.name.includes(frag)); if (!p) throw new Error('faq.js: no product matching ' + frag); return money(p.price); };
const inGroup = (c, s) => PRODUCTS.filter((p) => p.category === c && (!s || s === '*' || p.subcategory === s)).map((p) => p.price);
const lo = (c, s) => money(Math.min(...inGroup(c, s)));
const hi = (c, s) => money(Math.max(...inGroup(c, s)));
const SHIP = 495; // flat-rate hydraulic tail-lift freight (SHOP.shippingFee)

const d = {
  push: range((p) => p.category === 'push-pull-golf-buggies'),
  walk: range((p) => p.subcategory === 'walk-behind'),
  remote: range((p) => p.subcategory === 'remote-control-golf-buggies'),
  elec: range((p) => p.category === 'electric-golf-buggies' && p.subcategory !== 'conversion-kits'),
  cart: range((p) => p.category === 'luxury-golf-carts' && p.subcategory !== 'used'),
  cart46: range((p) => p.subcategory === '4-6-seat'),
  usedCart: range((p) => p.category === 'luxury-golf-carts' && p.subcategory === 'used'),
  usedAll: range((p) => p.condition === 'Used' || p.condition === 'Ex-Demo'),
  dune: range((p) => p.subcategory === 'dune-buggies'),
  speed: { min: Math.min(...speeds), max: Math.max(...speeds) },
  range: { min: Math.min(...ranges), max: Math.max(...ranges) },
};

/** Shared facts so blog posts and FAQs always quote the same numbers. */
export const FACTS = { ...d, ship: SHIP };
export { money };

export const FAQ_THEMES = ['Buying & prices', 'Delivery, payment & warranty', 'Speed, range & charging', 'Batteries & chargers', 'Parts & troubleshooting', 'Golf clubs & gear', 'Kids buggies', 'Road rules & licences', 'Off-road buggies'];

export const FAQ_BANK = [
  // ---------------- homepage set
  { id: 'cost-buggy', home: true, theme: 'Buying & prices', pages: ['/', '/shop/'], question: 'How much does a golf buggy cost in Australia?',
    answer: `Push golf buggies start at ${money(d.push.min)}. Electric walk-behind buggies run from ${money(d.walk.min)}, and remote-control models from ${money(d.remote.min)}. Ride-on golf carts start at ${money(d.cart.min)}. All prices include GST and delivery is a flat ${money(SHIP)} Australia-wide. Compare every model and filter by price in our shop.`,
    cta: { href: '/shop/', label: 'Browse all golf buggies' } },
  { id: 'cost-cart', home: true, theme: 'Buying & prices', pages: ['/', '/shop/luxury-golf-carts/'], question: 'How much does an electric golf cart cost?',
    answer: `New electric golf carts start at ${money(d.cart.min)} for a 2-seater, and 4 to 6 seat carts start at ${money(d.cart46.min)}. Used and ex-fleet carts start from ${money(d.usedCart.min)}. Prices include GST, and delivery is a flat ${money(SHIP)} Australia-wide. Browse every cart in our golf cart range.`,
    cta: { href: '/shop/luxury-golf-carts/', label: 'See golf carts for sale' } },
  { id: 'best-electric', home: true, theme: 'Buying & prices', pages: ['/', '/shop/electric-golf-buggies/'], question: 'What is the best electric golf buggy in Australia?',
    answer: `For most golfers, a lithium remote-control or walk-behind buggy from MGI, Motocaddy, PowaKaddy or Stewart Golf is the right pick. Our electric range runs from ${money(d.elec.min)} to ${money(d.elec.max)}. Choose remote control for hands-free, or walk-behind to save money. Compare them in our electric golf buggy range.`,
    cta: { href: '/shop/electric-golf-buggies/', label: 'Compare electric golf buggies' } },
  { id: 'delivery', home: true, theme: 'Delivery, payment & warranty', pages: ['/', '/golf-buggies/'], question: 'Do you deliver golf buggies Australia-wide?',
    answer: `Yes. We deliver nationwide by hydraulic tail-lift truck to your property gate or clubhouse for a flat ${money(SHIP)} per order. We are based in Queensland and ship to every state. Call 0480 811 308 or check delivery times for your city.`,
    cta: { href: '/golf-buggies/', label: 'Delivery by city' } },
  { id: 'payment', home: true, theme: 'Delivery, payment & warranty', pages: ['/'], question: 'What payment options do you offer?',
    answer: 'Pay by bank transfer (Osko or EFT), PayID, or split the cost into four equal payments at 0% interest. Pay with Bitcoin or USDT and take 10% off. All prices include GST. You choose at checkout and we email payment details with your order reference. See our finance options.',
    cta: { href: '/finance/', label: 'Pay in 4 and finance options' } },
  { id: 'warranty', home: true, theme: 'Delivery, payment & warranty', pages: ['/', '/shop/electric-golf-buggies/'], question: 'Is there a warranty on new golf buggies?',
    answer: 'New lithium golf buggies include a 5-year LiFePO4 battery guarantee, and each product page lists the warranty that applies to that model. We support what we sell from our Queensland base. Ask which warranty applies before you order, or call 0480 811 308.',
    cta: { href: '/shop/electric-golf-buggies/', label: 'See electric golf buggies' } },
  { id: 'used', home: true, theme: 'Buying & prices', pages: ['/', '/shop/used-golf-buggies/'], question: 'Can I buy a used golf buggy?',
    answer: `Yes. We stock inspected used and ex-demo golf buggies and carts from ${money(d.usedAll.min)}, including MGI ex-demo buggies and ex-fleet E-Z-GO, Club Car and Yamaha carts. Each one is checked before sale and comes with local support. Stock changes often, so message us on WhatsApp for what has just arrived.`,
    cta: { href: '/shop/used-golf-buggies/', label: 'See used golf buggies' } },
  { id: 'bundle', home: true, theme: 'Buying & prices', pages: ['/', '/shop/accessories/'], question: 'Do I get a discount on accessories when I buy a buggy?',
    answer: 'Yes. When your order includes a golf buggy or cart, every accessory and part in it is 5% off, applied automatically at checkout. Paying with crypto takes a further 10% off the order. Browse our accessories and parts before you check out.',
    cta: { href: '/shop/accessories/', label: 'Shop accessories' } },

  // ---------------- FAQ page and category pages
  { id: 'buggy-vs-cart', theme: 'Buying & prices', pages: ['/faq/'], question: 'What is the difference between a golf buggy and a golf cart?',
    answer: `In Australia a golf buggy usually means a wheeled trolley you walk behind, either push or electric. A golf cart is a ride-on electric vehicle that carries two to six people. We sell both: buggies from ${money(d.push.min)} and carts from ${money(d.cart.min)}.`,
    cta: { href: '/shop/', label: 'Browse buggies and carts' } },
  { id: 'electric-or-gas', theme: 'Buying & prices', pages: ['/faq/'], question: 'Are golf carts electric or petrol?',
    answer: 'Most modern golf carts are electric, and all our golf buggies are electric. Petrol is more common in off-road buggies such as dune buggies and some farm UTVs. Browse electric carts in our golf cart range, or petrol buggies in our off-road range.',
    cta: { href: '/shop/luxury-golf-carts/', label: 'See electric golf carts' } },
  { id: 'speed', theme: 'Speed, range & charging', pages: ['/faq/', '/shop/luxury-golf-carts/'], question: 'How fast does an electric golf cart go?',
    answer: `Top speeds of the golf carts we list run from ${d.speed.min} km/h to ${d.speed.max} km/h, and each product page shows the figure for that model. Some carts are speed-limited for golf course use, and road-compliant models are noted on their pages. Compare models side by side in our golf cart range.`,
    cta: { href: '/shop/luxury-golf-carts/', label: 'Compare golf carts' } },
  { id: 'range', theme: 'Speed, range & charging', pages: ['/faq/', '/shop/luxury-golf-carts/'], question: 'How far can an electric golf cart go on one charge?',
    answer: `The ride-on golf carts we list show a range of ${d.range.min} km to ${d.range.max}+ km per charge, depending on the battery and terrain. Lithium LiFePO4 models usually go furthest. Each product page lists the range for that cart, so you can compare models before you buy.`,
    cta: { href: '/shop/luxury-golf-carts/', label: 'See cart ranges' } },
  { id: 'charge', theme: 'Speed, range & charging', pages: ['/faq/', '/shop/chargers/'], question: 'How do you charge an electric golf cart?',
    answer: 'Plug the charger that suits your battery into a power outlet and leave it until it finishes. Lithium and lead-acid batteries need different chargers, so never swap them. We stock lithium and lead-acid chargers and leads, and can confirm the right one if you call.',
    cta: { href: '/shop/chargers/', label: 'Golf buggy chargers' } },
  { id: 'battery-life', theme: 'Speed, range & charging', pages: ['/faq/', '/shop/batteries/'], question: 'How long does an electric golf cart battery last?',
    answer: 'Lithium LiFePO4 batteries are rated for thousands of charge cycles and last far longer than lead-acid. New lithium buggies from us carry a 5-year LiFePO4 guarantee. Lead-acid sets need replacing sooner. See upgrade and replacement options in our battery range.',
    cta: { href: '/shop/batteries/', label: 'Batteries and lithium upgrades' } },
  { id: 'road-legal', theme: 'Road rules & licences', pages: ['/faq/'], question: 'Are golf carts and buggies road legal in Australia?',
    answer: 'Road rules are set by each state, and a cart used only on private land or a course is treated differently from one driven on public roads. We provide conditional registration compliance support for QLD, NSW and VIC on models marked road compliant. Read our registration guide for the detail.',
    cta: { href: '/blog/conditional-road-registration-guide-qld-nsw-vic/', label: 'Read the registration guide' } },
  { id: 'licence', theme: 'Road rules & licences', pages: ['/faq/'], question: 'Do you need a licence to drive a golf cart?',
    answer: 'On public roads you need a licence and a registered, compliant vehicle. On private land such as a farm, estate or golf course, road licence rules apply differently, and clubs or insurers may set their own. Check with your state road authority or call 0480 811 308 for advice before you buy.',
    cta: { href: '/contact/', label: 'Ask our sales desk' } },
  { id: 'dune', theme: 'Off-road buggies', pages: ['/faq/', '/shop/dune-buggies/'], question: 'What is a dune buggy?',
    answer: `A dune buggy, also called a beach buggy, is a light off-road vehicle with big rear tyres built for sand, dirt and tracks. Ours are petrol models from 110cc to 300cc and start at ${money(d.dune.min)}. Each model page lists its engine size and specifications so you can compare before you order.`,
    cta: { href: '/shop/dune-buggies/', label: 'See dune buggies' } },
  { id: 'dune-legal', theme: 'Off-road buggies', pages: ['/faq/', '/shop/dune-buggies/'], question: 'Are dune buggies road legal?',
    answer: 'Dune and off-road buggies are sold for use on private land, farms and recreation areas, not as road vehicles. Using one on public roads requires meeting your state registration rules, which most do not. Ask our team about your state.',
    cta: { href: '/shop/off-road-buggies/', label: 'See off-road buggies' } },

  // ---------------- keyword engine v2 additions (6 Oct 2026): batteries, parts, golf gear, kids buggies, brands
  { id: 'battery-cost-buggy', theme: 'Batteries & chargers', pages: ['/faq/', '/shop/batteries/'], question: "How much does a golf buggy battery cost?",
    answer: `Golf buggy batteries on our range cost from ${lo('batteries', 'lithium')} to ${hi('batteries', 'lithium')}, including MGI, Motocaddy and aftermarket lithium packs and a lead-acid option. Chargers are extra, from ${pr('Lead-Acid Buggy Charger')}. See our golf buggy batteries for the full list. Packs for 18-hole and 36-hole rounds are both available, so you only pay for the range you need.`,
    cta: { href: '/shop/batteries/', label: "Browse golf buggy batteries" } },
  { id: 'battery-cost-cart', theme: 'Batteries & chargers', pages: ['/faq/', '/shop/cart-sets/'], question: "How much do golf cart batteries cost?",
    answer: `A 48V golf cart battery set on our range costs from ${lo('batteries', 'cart-sets')} to ${hi('batteries', 'cart-sets')}. Flooded lead-acid sets are at the lower end; AGM and lithium are higher. The GIANT 48V 100Ah lithium drop-in is ${pr('GIANT 48V')}. Browse golf cart batteries. Check each listing for what is included.`,
    cta: { href: '/shop/cart-sets/', label: "Browse golf cart batteries" } },
  { id: 'battery-size', theme: 'Batteries & chargers', pages: ['/faq/', '/shop/lithium/'], question: "What size battery does my golf buggy need?",
    answer: `Match the voltage, hole rating and connector of the original pack. We stock 12V 18-hole and 24V 36-hole lithium packs plus a 24V 13Ah remote-series pack for MGI buggies, from ${lo('batteries', 'lithium')}. Check your manual or the label on the old battery first.`,
    cta: { href: '/shop/lithium/', label: "Browse lithium golf buggy batteries" } },
  { id: 'battery-lithium-swap', theme: 'Batteries & chargers', pages: ['/faq/', '/shop/lithium/'], question: "Can I put a lithium battery in an old golf buggy?",
    answer: `Usually yes: choose a lithium pack with the same voltage, check the connector, and use the matching lithium charger. We list lithium packs from ${lo('batteries', 'lithium')}, and a 12V lead-acid pack at ${pr('Lead-Acid 12V')} if you prefer to stay lead-acid. Always confirm compatibility before ordering.`,
    cta: { href: '/shop/lithium/', label: "Browse lithium golf buggy batteries" } },
  { id: 'parts-where', theme: 'Parts & troubleshooting', pages: ['/faq/', '/shop/parts/'], question: "Where can I buy golf buggy parts in Australia?",
    answer: `Our parts range covers wheels, tyres, motors, controllers and trim for MGI, Clicgear, Stinger and aftermarket buggies, from ${lo('parts', 'drive-electrical')} to ${hi('parts', 'drive-electrical')} for drive and electrical parts. Browse golf buggy parts, or contact us on 0480 811 308 for a part you cannot find.`,
    cta: { href: '/shop/parts/', label: "Browse golf buggy parts" } },
  { id: 'cart-wont-start', theme: 'Parts & troubleshooting', pages: ['/faq/', '/shop/parts/'], question: "Why will my golf cart not turn on?",
    answer: `Start with the basics: check the battery charge, the main connector and any fuse, then the charger. A dead or deeply discharged battery is the most common cause. If the pack is fine, the controller or key switch is next. Browse golf buggy parts for replacements.`,
    cta: { href: '/shop/parts/', label: "Browse golf buggy parts" } },
  { id: 'ac-vs-dc', theme: 'Buying & prices', pages: ['/faq/', '/shop/luxury-golf-carts/'], question: "What does AC mean on a golf cart?",
    answer: `AC means the cart uses an alternating-current motor. It is more efficient than an older DC motor, has no brushes to wear out and supports regenerative braking on hills. Our ECAR Lithium A2 and A4 carts use 4.0kW AC systems. Browse golf carts for sale to compare.`,
    cta: { href: '/shop/luxury-golf-carts/', label: "Browse golf carts for sale" } },
  { id: 'used-cart-price', theme: 'Buying & prices', pages: ['/faq/', '/shop/used-golf-buggies/'], question: "How much is a used golf cart in Australia?",
    answer: `Our used and ex-lease golf carts run from ${lo('luxury-golf-carts', 'used')} to ${hi('luxury-golf-carts', 'used')}, with an ex-demo MGI buggy at ${pr('Ex-Demo MGI')}. Price depends on seats, battery type and age. See used golf carts for the current list. Delivery is flat-rate by tail-lift truck, Australia-wide.`,
    cta: { href: '/shop/used-golf-buggies/', label: "See used golf buggies" } },
  { id: 'wedge-sand', theme: 'Golf clubs & gear', pages: ['/faq/', '/shop/wedges-and-putters/'], question: "What degrees is a sand wedge?",
    answer: `A sand wedge is usually 54 to 56 degrees of loft, although sets range from 52 to 58 degrees. It is used for bunker shots and short pitches around the green. Choose its loft to sit 4 to 6 degrees above your gap wedge. See golf wedges.`,
    cta: { href: '/shop/wedges-and-putters/', label: "Browse golf wedges and putters" } },
  { id: 'loft-def', theme: 'Golf clubs & gear', pages: ['/faq/'], question: "What is loft in golf?",
    answer: `Loft is the angle of the clubface relative to vertical. More loft launches the ball higher and shorter with more backspin; less loft sends it lower and further. A driver is about 9 to 12 degrees and a lob wedge 58 to 62 degrees.`,
    cta: { href: '/blog/golf-wedge-degrees-loft-guide/', label: "Read the wedge loft guide" } },
  { id: 'clubs-needed', theme: 'Golf clubs & gear', pages: ['/faq/', '/shop/complete-sets/'], question: "What golf clubs do you need as a beginner?",
    answer: `The Rules of Golf allow up to 14 clubs, but a beginner can start with 12: a driver, a fairway wood or hybrid, irons, a wedge and a putter. Our 12-piece beginner set is ${pr('Beginner Complete')}. See complete golf club sets.`,
    cta: { href: '/shop/complete-sets/', label: "Browse golf club sets" } },
  { id: 'rangefinder-vs-watch', theme: 'Golf clubs & gear', pages: ['/faq/', '/shop/rangefinders-gps/'], question: "Is a golf rangefinder better than a GPS watch?",
    answer: `Neither is better for everyone. A laser rangefinder gives the exact distance to the flag but needs line of sight; a GPS watch gives front, middle and back distances hands-free. Rangefinders here start at ${pr('Precision Pro NX7')}, watches at ${pr('Shot Scope G5')}. Pick the one that matches how you like to play.`,
    cta: { href: '/shop/rangefinders-gps/', label: "Browse rangefinders and GPS watches" } },
  { id: 'bag-for-buggy', theme: 'Golf clubs & gear', pages: ['/faq/', '/shop/bags/'], question: "What golf bag is best for a golf buggy?",
    answer: `A cart bag is best for a buggy or trolley because the flat top and full-length dividers keep clubs organised and the base sits securely on the frame. Our cart bags are ${pr('Golf Cart Bag')} and ${pr('Big Max Dri Lite')}. See golf bags. Check the divider layout suits your clubs.`,
    cta: { href: '/shop/bags/', label: "Browse golf bags" } },
  { id: 'junior-set', theme: 'Golf clubs & gear', pages: ['/faq/', '/shop/complete-sets/'], question: "How much is a kids golf club set?",
    answer: `Our Junior Golf Club Set is ${pr('Junior Golf Club Set')}. Children outgrow clubs, so a complete junior set is usually better value than buying clubs one at a time. See junior and complete golf club sets. Ask us about sizing before you order if you are unsure of your child's height.`,
    cta: { href: '/shop/complete-sets/', label: "Browse golf club sets" } },
  { id: 'ladies-set', theme: 'Golf clubs & gear', pages: ['/faq/', '/shop/complete-sets/'], question: "Do you sell a complete ladies golf club set?",
    answer: `Yes. Our Ladies' Complete Golf Club Set is ${pr('Ladies')}. It is a full set for women, so you can start playing without buying clubs one at a time. See complete golf club sets. Ask us if you are unsure which flex suits you.`,
    cta: { href: '/shop/complete-sets/', label: "Browse golf club sets" } },
  { id: 'cart-brands', theme: 'Buying & prices', pages: ['/faq/'], question: "Which golf cart brands do you stock?",
    answer: `We stock Club Car, Yamaha, E-Z-GO, ECAR, Tomberlin, Evolution, Tara, Garia, Cougar, Rippa, Shelby and LVTONG, new and used. Prices run from ${lo('luxury-golf-carts', '*')} for new carts. See our brands page to compare each brand. Used carts from several brands are also listed.`,
    cta: { href: '/brands/', label: "Browse all brands" } },
  { id: 'mgi-choose', theme: 'Buying & prices', pages: ['/faq/'], question: "Which MGI golf buggy should I buy?",
    answer: `The Zip X1 at ${pr('MGI Zip X1')} is the entry model. The X5 at ${pr('MGI Zip X5')} adds downhill braking. For hands-free walking, choose a remote model such as the Ai 500 at ${pr('MGI Ai 500')} or a GPS follow model. See MGI golf buggies. Check each listing for what is included.`,
    cta: { href: '/brands/mgi/', label: "See MGI golf buggies" } },
  { id: 'kids-road', theme: 'Kids buggies', pages: ['/faq/', '/shop/kids-buggies/'], question: "Can kids ride a buggy on the road?",
    answer: `No. Kids buggies are built for private land and are not road registered, so they should not be ridden on public roads. Check your state rules for riding on rural property, and always supervise. Browse kids buggies designed for private-property use.`,
    cta: { href: '/shop/kids-buggies/', label: "See kids buggies" } },
  { id: 'kids-power', theme: 'Kids buggies', pages: ['/faq/', '/shop/kids-buggies/'], question: "Are kids off-road buggies electric or petrol?",
    answer: `Both. Our electric kids buggies run on 24V to 48V and start at ${lo('kids-buggies', 'electric')}, while the petrol models run 90cc to 208cc and cost ${lo('kids-buggies', 'petrol')} to ${hi('kids-buggies', 'petrol')}. Electric is quieter and simpler; petrol has more power. See kids buggies for sale.`,
    cta: { href: '/shop/kids-buggies/', label: "See kids buggies" } },
  { id: 'ac-vs-dc-better', theme: 'Buying & prices', pages: ['/blog/golf-cart-ac-vs-dc-motor-guide/'], question: "Is an AC golf cart better than DC?",
    answer: `For most buyers yes. AC drives are generally more efficient, need less maintenance and brake smoothly downhill. DC carts cost less to buy and are simple to repair, so they suit tight budgets and older ex-lease carts. Both are covered by our used and new ranges.`,
    cta: { href: '/shop/luxury-golf-carts/', label: "Browse golf carts for sale" } },
  { id: 'used-auction-safe', theme: 'Buying & prices', pages: ['/blog/used-golf-cart-auction-vs-dealer-australia/'], question: "Is it safe to buy a used golf cart at auction?",
    answer: `It can be, but auction carts are normally sold as-is with no warranty and no test drive. Ask for the battery age, check the controller and brakes, and budget for a battery replacement. A dealer cart costs more but comes with inspection and cover.`,
    cta: { href: '/shop/used-golf-buggies/', label: "See used golf buggies" } },
  { id: 'used-cart-check', theme: 'Buying & prices', pages: ['/blog/used-golf-cart-auction-vs-dealer-australia/'], question: "What should I check on a used golf cart?",
    answer: `Check battery age and health, the motor and controller, brakes, tyres, chassis rust, charger, and the serial plate. Always test drive it on a slope. Lithium carts should show battery health, as on our tested 98%+ ex-demo buggy. Ask for service records.`,
    cta: { href: '/shop/used-golf-buggies/', label: "See used golf buggies" } },
  { id: 'mgi-zip-vs-ai', theme: 'Buying & prices', pages: ['/blog/mgi-zip-vs-ai-navigator-which-mgi-buggy/'], question: "What is the difference between the MGI Zip and the MGI Ai?",
    answer: `The Zip range is walk-behind: you steer the buggy by the handle. The Ai Navigator range adds GPS follow so the buggy tracks you around the course, and the Ai 500 and Zip Navigator AT are remote-controlled. The Zip X1 starts at ${pr('MGI Zip X1')}.`,
    cta: { href: '/brands/mgi/', label: "See MGI golf buggies" } },
  { id: 'mgi-hills', theme: 'Buying & prices', pages: ['/blog/mgi-zip-vs-ai-navigator-which-mgi-buggy/'], question: "Which MGI golf buggy is best for hills?",
    answer: `The MGI Zip X5 has downhill braking, so it holds its speed on slopes. Choose a remote or GPS model if you want to walk free of the handle. The X5 is ${pr('MGI Zip X5')}. See walk-behind buggies for the full range.`,
    cta: { href: '/brands/mgi/', label: "See MGI golf buggies" } },
  { id: 'mgi-battery', theme: 'Buying & prices', pages: ['/blog/mgi-zip-vs-ai-navigator-which-mgi-buggy/'], question: "Do MGI buggies come with a lithium battery?",
    answer: `Our MGI buggies use lithium packs, and replacements are stocked as 12V 18-hole and 24V 36-hole packs plus a 24V remote-series pack. Check each product page for the battery listed with that model, and see MGI lithium batteries. Packs are sold separately if you need a spare.`,
    cta: { href: '/brands/mgi/', label: "See MGI golf buggies" } },
  { id: 'battery-replace-when', theme: 'Batteries & chargers', pages: ['/blog/golf-cart-battery-replacement-cost-australia/'], question: "How often should golf cart batteries be replaced?",
    answer: `Replace them when range drops noticeably, the cart charges slowly, or a battery fails a load test. Lead-acid sets generally need replacing sooner than lithium. Check each pack against its stated warranty, and see our guide to lithium versus lead-acid lifespan.`,
    cta: { href: '/shop/cart-sets/', label: "Browse golf cart batteries" } },
  { id: 'buggy-service-often', theme: 'Parts & troubleshooting', pages: ['/blog/golf-buggy-repairs-servicing-guide-australia/'], question: "How often should a golf buggy be serviced?",
    answer: `Check wheels, tyres, bolts and connectors monthly, keep the battery charged after each round, and clean it after wet rounds. Replace tyres and wheels when worn. Our wheels and tyres range runs from ${lo('parts', 'wheels-tyres')} to ${hi('parts', 'wheels-tyres')}. A quick check after each wet round catches problems early.`,
    cta: { href: '/shop/parts/', label: "Browse golf buggy parts" } },
  { id: 'wedge-pitching', theme: 'Golf clubs & gear', pages: ['/blog/golf-wedge-degrees-loft-guide/'], question: "What is the loft of a pitching wedge?",
    answer: `A pitching wedge is typically 44 to 48 degrees. Modern game-improvement sets use stronger lofts, so check the loft stamped on your own club. A gap wedge of 50 to 52 degrees then fills the distance gap to your sand wedge.`,
    cta: { href: '/shop/wedges-and-putters/', label: "Browse golf wedges and putters" } },
  { id: 'putter-beginner', theme: 'Golf clubs & gear', pages: ['/blog/best-golf-putters-types-guide-australia/'], question: "What type of putter is best for beginners?",
    answer: `A mallet putter is usually best for beginners because it is more forgiving on off-centre hits and helps with alignment. Choose a standard length that suits your height, then adjust. Our Golf Putter is ${pr('Golf Putter')}; see golf putters for sale.`,
    cta: { href: '/shop/wedges-and-putters/', label: "Browse golf wedges and putters" } },
  { id: 'putter-blade-mallet', theme: 'Golf clubs & gear', pages: ['/blog/best-golf-putters-types-guide-australia/'], question: "What is the difference between a blade and a mallet putter?",
    answer: `A blade putter is slim with a toe-hang that suits an arcing stroke; a mallet is larger, more stable and more forgiving on mishits. Mallets are generally easier for beginners. Many golfers test both before choosing. Try both on a practice green if you can.`,
    cta: { href: '/shop/wedges-and-putters/', label: "Browse golf wedges and putters" } },
  { id: 'clubs-14', theme: 'Golf clubs & gear', pages: ['/blog/what-golf-clubs-do-you-need-full-set-explained/'], question: "How many golf clubs are you allowed to carry?",
    answer: `The Rules of Golf allow a maximum of 14 clubs in your bag. Most beginners carry fewer: a driver, a fairway wood or hybrid, a few irons, a wedge and a putter. Our beginner complete set is 12 pieces at ${pr('Beginner Complete')}.`,
    cta: { href: '/shop/complete-sets/', label: "Browse golf club sets" } },
  { id: 'set-best-beginner', theme: 'Golf clubs & gear', pages: ['/blog/best-golf-club-sets-for-beginners-australia/'], question: "What is the best golf club set for a beginner?",
    answer: `A complete 10 to 12 piece set with a driver, fairway wood or hybrid, irons, wedge and putter is the best start. Ours is a 12-piece beginner set at ${pr('Beginner Complete')}. Choose men, ladies or junior sizing before you buy, and check what is included.`,
    cta: { href: '/shop/complete-sets/', label: "Browse golf club sets" } },
  { id: 'set-spend', theme: 'Golf clubs & gear', pages: ['/blog/best-golf-club-sets-for-beginners-australia/'], question: "How much should I spend on a first set of golf clubs?",
    answer: `Most beginners are best served by a complete starter set rather than premium clubs. Our range starts at ${pr('Junior Golf Club Set')} for juniors and ${pr('Beginner Complete')} for adults. Upgrade individual clubs once your swing is consistent. Spend the difference on lessons rather than premium clubs.`,
    cta: { href: '/shop/complete-sets/', label: "Browse golf club sets" } },
  { id: 'junior-size', theme: 'Kids buggies', pages: ['/blog/junior-golf-clubs-kids-golf-sets-by-age/'], question: "What size golf clubs does my child need?",
    answer: `Junior clubs are sized by height more than age. Measure your child, check the manufacturer chart, and choose a set that lets them hold the club comfortably without it being too heavy. Our junior set is ${pr('Junior Golf Club Set')}. Growing juniors may need new clubs every couple of years.`,
    cta: { href: '/shop/complete-sets/', label: "Browse golf club sets" } },
  { id: 'ladies-diff', theme: 'Golf clubs & gear', pages: ['/blog/ladies-golf-clubs-womens-golf-sets-guide/'], question: "What is the difference between ladies and men's golf clubs?",
    answer: `Ladies clubs are usually lighter and shorter with a more flexible shaft, which suits slower swing speeds and helps get the ball airborne. Men's clubs are longer and stiffer. Choose by swing speed and height rather than label alone. Fit matters more than the label.`,
    cta: { href: '/shop/complete-sets/', label: "Browse golf club sets" } },
  { id: 'bag-stand-on-buggy', theme: 'Golf clubs & gear', pages: ['/blog/golf-bag-and-cart-how-to-choose-stand-cart-carry/'], question: "Can I use a stand bag on a golf buggy?",
    answer: `Yes, but a stand bag's legs and shape can sit awkwardly on a buggy frame. Straps usually hold it in place for a casual round, though a cart bag is more stable. Our Lightweight Golf Stand Bag is ${pr('Lightweight Golf Stand')}. Test the fit before a round.`,
    cta: { href: '/shop/bags/', label: "Browse golf bags" } },
  { id: 'rangefinder-tournament', theme: 'Golf clubs & gear', pages: ['/blog/golf-rangefinder-vs-gps-watch-which-to-buy/'], question: "Are golf rangefinders allowed in tournaments?",
    answer: `Distance-measuring devices are widely allowed, but rangefinders with slope functions are often banned in competitions. Check your club or event's local rules before you play a tournament round. Our Bushnell Tour V5 and Pro X3 are listed with their features.`,
    cta: { href: '/shop/rangefinders-gps/', label: "Browse rangefinders and GPS watches" } },
  { id: 'driver-loft', theme: 'Golf clubs & gear', pages: ['/blog/how-to-choose-a-golf-driver/'], question: "What loft driver should I buy?",
    answer: `Most golfers do well with 10.5 degrees. Faster swings can use 9 degrees; slower swings, seniors and many beginners benefit from 12 degrees for easier launch. Our Golf Driver is ${pr('Golf Driver')}. See golf drivers for sale. A fitting session will confirm the best loft.`,
    cta: { href: '/shop/woods-and-irons/', label: "Browse golf driver" } },
  { id: 'driver-vs-wood', theme: 'Golf clubs & gear', pages: ['/blog/how-to-choose-a-golf-driver/'], question: "What is the difference between a driver and a fairway wood?",
    answer: `A driver has the largest head and lowest loft for maximum distance off the tee. A fairway wood is smaller with more loft, so it is easier to hit from the fairway. Many beginners carry a driver and a 3 or 5 wood.`,
    cta: { href: '/shop/woods-and-irons/', label: "Browse golf driver" } },
  { id: 'iron-how-many', theme: 'Golf clubs & gear', pages: ['/blog/how-to-choose-an-iron-set/'], question: "How many irons are in a set?",
    answer: `A standard iron set has 7 or 8 clubs, usually 4 or 5 iron through pitching wedge. Beginners often start with a 6-iron to pitching wedge set plus a hybrid. Our Mid-Range Golf Iron Set is ${pr('Mid-Range Golf Iron')}. See golf irons for sale.`,
    cta: { href: '/shop/woods-and-irons/', label: "Browse golf irons for sale" } },
  { id: 'iron-cavity', theme: 'Golf clubs & gear', pages: ['/blog/how-to-choose-an-iron-set/'], question: "Are cavity back irons better for beginners?",
    answer: `Yes. Cavity-back irons spread weight to the edges, making off-centre hits straighter and longer, so they are the best choice for beginners and mid-handicappers. Blades suit skilled players who want shot-shaping control. Most modern game-improvement iron sets use this design today.`,
    cta: { href: '/shop/woods-and-irons/', label: "Browse golf irons for sale" } },
];

// Backwards-compatible export used by the homepage and the FAQ component
export const HOMEPAGE_FAQS = FAQ_BANK.filter((f) => f.home);

/** FAQs written for a given page path, e.g. faqsForPage('/shop/luxury-golf-carts/') */
export const faqsForPage = (url) => FAQ_BANK.filter((f) => f.pages.includes(url));

/** Plain-text word count (used by the crosscheck). */
export const faqWords = (text) => text.trim().split(/\s+/).length;
