// src/config/products.js
// Australian Golf Buggy Products Catalog (WebForge v11.1 AU)
// Adheres strictly to floor pricing: Electric >= $1,000 | Manual Push >= $450 | Kids >= $850 | Inc. GST | Australian English
// Real Market Competitor Pricing based on Google AU SERP Analysis (Drummond, GolfBox, Carts'n'Parts, Golf Cars Australia)

export const PRODUCTS = [
  // ==========================================
  // 1. ELECTRIC GOLF BUGGIES - REMOTE CONTROL
  // ==========================================
  {
    slug: 'mgi-zip-navigator-at-remote-electric-golf-buggy',
    name: 'MGI Zip Navigator AT Remote Control Electric Golf Buggy',
    brand: 'mgi',
    brandName: 'MGI',
    category: 'remote-control-golf-buggies',
    categoryPath: '/remote-control-golf-buggies/',
    price: 2099,
    condition: 'New',
    badge: 'Australia #1 Remote',
    featured: true,
    rating: 4.9,
    reviewCount: 257,
    power: 'Remote control',
    wheels: '4-wheel',
    batteryRange: '36 hole',
    weightCategory: '10–13 kg',
    weightKg: 13.0,
    foldSize: 'Compact / flat-fold',
    seats: 'Walk-behind',
    primaryKeyword: 'mgi zip navigator at remote electric golf buggy',
    shortDescription: 'Australia\'s best-selling all-terrain remote control golf buggy with dual 230W motors, gyroscope straight-tracker, and 36-hole 24V lithium battery.',
    description: 'The MGI Zip Navigator AT (All-Terrain) is Australia\'s benchmark remote-control electric golf buggy. Engineered with dual 230-watt calibrated motors and patented Gyroscope Straight Tracker technology that automatically corrects alignment across steep Australian side-slopes. Features a directional remote handset with forward, reverse, left, right and speed control, all-terrain rear tread tyres, foldable 4th rear stabiliser wheel, and a Click & Go 24V 380Wh lithium battery delivering 36+ holes per charge.',
    specs: {
      power: 'Remote control (Full Directional Wireless Handset)',
      motor: 'Twin 230W Calibrated Low-Noise Motors',
      battery: '24V 380Wh Click & Go Lithium (36+ Hole Capacity)',
      weight: '13.0 kg (Without Battery) / 15.8 kg (With Battery)',
      wheels: '4-Wheel All-Terrain with Foldable Rear Stabiliser',
      foldSize: '70cm x 47cm x 42cm (Inverted Rear Wheels)',
      brakes: 'Downhill Speed Control & Electronic Park Brake',
      warranty: '3-Year Australian Manufacturer Warranty'
    },
    images: [
      '/images/products/mgi-zip-navigator-at-remote-electric-golf-buggy/main.webp',
      '/images/products/mgi-zip-navigator-at-remote-electric-golf-buggy/gallery-2.webp',
      '/images/products/mgi-zip-navigator-at-remote-electric-golf-buggy/gallery-3.webp',
      '/images/products/mgi-zip-navigator-at-remote-electric-golf-buggy/gallery-4.webp',
      '/images/products/mgi-zip-navigator-at-remote-electric-golf-buggy/gallery-5.webp',
      '/images/products/mgi-zip-navigator-at-remote-electric-golf-buggy/gallery-6.webp',
      '/images/products/mgi-zip-navigator-at-remote-electric-golf-buggy/gallery-7.webp'
    ]
  },
  {
    slug: 'mgi-ai-500-remote-electric-golf-buggy',
    name: 'MGI Ai 500 Remote Electric Golf Buggy',
    brand: 'mgi',
    brandName: 'MGI',
    category: 'remote-control-golf-buggies',
    categoryPath: '/remote-control-golf-buggies/',
    price: 1870,
    condition: 'New',
    badge: 'Intelligent Remote',
    featured: false,
    rating: 4.8,
    reviewCount: 45,
    power: 'Remote control',
    wheels: '4-wheel',
    batteryRange: '36 hole',
    weightCategory: '10–13 kg',
    weightKg: 12.8,
    foldSize: 'Compact / flat-fold',
    seats: 'Walk-behind',
    primaryKeyword: 'mgi ai 500 remote golf buggy',
    shortDescription: 'Smart directional remote control golf buggy with ergonomic ergonomic chassis and 36-hole 24V lithium battery.',
    description: 'The MGI Ai 500 brings next-generation remote intelligence to the fairway. Built on MGI\'s refined Ai architecture, it features full directional remote control, responsive speed dialling, automatic downhill speed regulation, and ultra-compact folding geometry.',
    specs: {
      power: 'Full Directional Remote Control',
      motor: 'Twin Calibrated 230W Electric Motors',
      battery: '24V 299Wh Lithium Battery Pack',
      weight: '12.8 kg (Chassis)',
      wheels: '4-Wheel Stable Stance',
      foldSize: '69cm x 46cm x 41cm',
      brakes: 'Electronic Downhill Speed Control',
      warranty: '3-Year Australian Warranty'
    },
    images: [
      '/images/products/mgi-ai-500-remote-electric-golf-buggy/main.webp',
      '/images/products/mgi-ai-500-remote-electric-golf-buggy/gallery-2.webp',
      '/images/products/mgi-ai-500-remote-electric-golf-buggy/gallery-3.webp',
      '/images/products/mgi-ai-500-remote-electric-golf-buggy/gallery-4.webp',
      '/images/products/mgi-ai-500-remote-electric-golf-buggy/gallery-5.webp',
      '/images/products/mgi-ai-500-remote-electric-golf-buggy/gallery-6.webp',
      '/images/products/mgi-ai-500-remote-electric-golf-buggy/gallery-7.webp',
      '/images/products/mgi-ai-500-remote-electric-golf-buggy/gallery-8.webp',
      '/images/products/mgi-ai-500-remote-electric-golf-buggy/gallery-9.webp',
      '/images/products/mgi-ai-500-remote-electric-golf-buggy/gallery-10.webp'
    ]
  },
  {
    slug: 'motocaddy-m7-remote-electric-golf-buggy',
    name: 'Motocaddy M7 Remote Control Electric Golf Buggy',
    brand: 'motocaddy',
    brandName: 'Motocaddy',
    category: 'remote-control-golf-buggies',
    categoryPath: '/remote-control-golf-buggies/',
    price: 1615,
    condition: 'New',
    badge: 'Most Wanted Winner',
    featured: true,
    rating: 4.9,
    reviewCount: 74,
    power: 'Remote control',
    wheels: '4-wheel',
    batteryRange: '36 hole',
    weightCategory: '10–13 kg',
    weightKg: 12.6,
    foldSize: 'Compact / flat-fold',
    seats: 'Walk-behind',
    primaryKeyword: 'motocaddy m7 remote golf buggy',
    shortDescription: 'Award-winning compact folding remote buggy with rechargeable ergonomic handset, dual 28.8V brushless motors, and anti-tip wheel.',
    description: 'Winner of multiple MyGolfSpy "Most Wanted" awards, the Motocaddy M7 Remote provides ultra-responsive directional handling, automatic Downhill Control (DHC), emergency brake function, and an anti-glare LCD screen.',
    specs: {
      power: 'Rechargeable Ergonomic Remote Handset',
      motor: 'Twin 230W Brushless 28.8V DHC Drive',
      battery: 'High Capacity 28.8V Ultra Lithium',
      weight: '12.6 kg',
      wheels: 'All-Terrain Low Profile DHC Wheels',
      foldSize: '65cm x 47cm x 42cm',
      brakes: 'Automatic Downhill Brake & Parking Brake',
      warranty: '2-Year Buggy / 5-Year Battery Warranty'
    },
    images: [
      '/images/products/motocaddy-m7-remote-electric-golf-buggy/main.webp',
      '/images/products/motocaddy-m7-remote-electric-golf-buggy/gallery-2.webp',
      '/images/products/motocaddy-m7-remote-electric-golf-buggy/gallery-3.webp'
    ]
  },
  {
    slug: 'stinger-golf-sg4-crossover-remote-electric-buggy',
    name: 'Stinger Golf SG-4 Crossover Remote Electric Buggy',
    brand: 'stinger',
    brandName: 'Stinger Golf',
    category: 'remote-control-golf-buggies',
    categoryPath: '/remote-control-golf-buggies/',
    price: 1220,
    condition: 'New',
    badge: 'Australian Owned',
    featured: false,
    rating: 4.8,
    reviewCount: 39,
    power: 'Remote control',
    wheels: '4-wheel',
    batteryRange: '36 hole',
    weightCategory: '10–13 kg',
    weightKg: 11.9,
    foldSize: 'Compact / flat-fold',
    seats: 'Walk-behind',
    primaryKeyword: 'stinger sg4 crossover remote golf buggy',
    shortDescription: 'Australian-designed remote control golf buggy featuring wide-track stability, dual whisper-quiet motors, and 36-hole lithium pack.',
    description: 'Designed specifically for Australian course conditions, the Stinger SG-4 Crossover delivers smooth remote navigation, wide-wheel stability across soft sand and wet turf, and quick one-step folding.',
    specs: {
      power: 'Digital Remote Handset with USB Charging',
      motor: 'Dual 200W Calibrated Electric Motors',
      battery: '24V 20Ah Lithium Battery',
      weight: '11.9 kg (Chassis)',
      wheels: '4-Wheel Wide Stance with Rear Wheelie Bar',
      foldSize: '68cm x 44cm x 39cm',
      brakes: 'Downhill Auto Brake',
      warranty: '2-Year Australian Replacement Guarantee'
    },
    images: [
      '/images/products/stinger-golf-sg4-crossover-remote-electric-buggy/main.webp',
      '/images/products/stinger-golf-sg4-crossover-remote-electric-buggy/gallery-2.webp',
      '/images/products/stinger-golf-sg4-crossover-remote-electric-buggy/gallery-3.webp',
      '/images/products/stinger-golf-sg4-crossover-remote-electric-buggy/gallery-4.webp',
      '/images/products/stinger-golf-sg4-crossover-remote-electric-buggy/gallery-5.webp',
      '/images/products/stinger-golf-sg4-crossover-remote-electric-buggy/gallery-6.webp',
      '/images/products/stinger-golf-sg4-crossover-remote-electric-buggy/gallery-7.webp'
    ]
  },
  {
    slug: 'alphard-cybercart-remote-electric-buggy',
    name: 'Alphard Cybercart Remote Control Electric Buggy',
    brand: 'alphard',
    brandName: 'Alphard Golf',
    category: 'remote-control-golf-buggies',
    categoryPath: '/remote-control-golf-buggies/',
    price: 1979,
    condition: 'New',
    badge: 'Cyber Frame Tech',
    featured: false,
    rating: 4.9,
    reviewCount: 68,
    power: 'Remote control',
    wheels: '4-wheel',
    batteryRange: '36 hole',
    weightCategory: '10–13 kg',
    weightKg: 13.2,
    foldSize: 'Compact / flat-fold',
    seats: 'Walk-behind',
    primaryKeyword: 'alphard cybercart remote golf buggy',
    shortDescription: 'Futuristic aerospace aluminium chassis with integrated dual brushless motors, Bluetooth tracking, and 36-hole lithium pack.',
    description: 'The Alphard Cybercart combines structural aerospace alloy with whisper-quiet digital remote transmission, Bluetooth companion app telematics, and an ultra-low center of gravity.',
    specs: {
      power: 'Wireless Remote Handset + Smartphone Control',
      motor: 'Integrated Dual Brushless High-Torque Hubs',
      battery: '36V Quick-Release Lithium Cartridge',
      weight: '13.2 kg',
      wheels: 'All-Terrain PU Solid Tyres',
      foldSize: '66cm x 46cm x 40cm',
      brakes: 'Intelligent Slope Assist & Downhill Braking',
      warranty: '2-Year Manufacturer Warranty'
    },
    images: [
      '/images/products/alphard-cybercart-remote-electric-buggy/main.webp'
    ]
  },
  {
    slug: 'explora-r1-remote-control-golf-buggy',
    name: 'Explora R1 Remote Electric Golf Buggy',
    brand: 'explora',
    brandName: 'Explora',
    category: 'remote-control-golf-buggies',
    categoryPath: '/remote-control-golf-buggies/',
    price: 1379,
    condition: 'New',
    badge: 'High Value Pick',
    featured: false,
    rating: 4.7,
    reviewCount: 31,
    power: 'Remote control',
    wheels: '4-wheel',
    batteryRange: '36 hole',
    weightCategory: '10–13 kg',
    weightKg: 12.2,
    foldSize: 'Compact / flat-fold',
    seats: 'Walk-behind',
    primaryKeyword: 'explora r1 remote golf buggy',
    shortDescription: 'Robust digital remote golf trolley with 36-hole lithium power, digital speedometer, and umbrella holder bundle.',
    description: 'The Explora R1 offers unbeatable remote-control performance under $1,400 AUD. Engineered with dual direct-drive motors, electronic gradient hold, and luxury accessory console.',
    specs: {
      power: 'Full Wireless Directional Remote',
      motor: 'Twin 180W Calibrated Motors',
      battery: '24V 20Ah Lithium Battery + Fast Charger',
      weight: '12.2 kg',
      wheels: '4-Wheel Stability Set',
      foldSize: '68cm x 45cm x 40cm',
      brakes: 'Downhill Speed Regulation',
      warranty: '2-Year Australian Warranty'
    },
    images: [
      '/images/products/explora-r1-remote-control-golf-buggy/main.webp',
      '/images/products/explora-r1-remote-control-golf-buggy/gallery-2.webp',
      '/images/products/explora-r1-remote-control-golf-buggy/gallery-3.webp'
    ]
  },

  // ==========================================
  // 2. WALK-BEHIND ELECTRIC GOLF BUGGIES
  // ==========================================
  {
    slug: 'mgi-zip-x1-electric-golf-buggy',
    name: 'MGI Zip X1 Electric Golf Buggy',
    brand: 'mgi',
    brandName: 'MGI',
    category: 'electric-golf-buggies',
    categoryPath: '/electric-golf-buggies/',
    price: 1099,
    condition: 'New',
    badge: 'Category Benchmark',
    featured: true,
    rating: 4.9,
    reviewCount: 180,
    power: 'Electric',
    wheels: '3-wheel',
    batteryRange: '36 hole',
    weightCategory: 'Under 10 kg',
    weightKg: 9.8,
    foldSize: 'Compact / flat-fold',
    seats: 'Walk-behind',
    primaryKeyword: 'mgi zip x1 electric golf buggy',
    shortDescription: 'Australia\'s favourite walk-behind motorized buggy with smooth variable speed dial, whisper-quiet 230W motor, and 24V lithium battery.',
    description: 'The MGI Zip X1 is Australia\'s standard for walk-behind electric golf buggies. Built with a responsive digital speed dial, whisper-quiet 230W motor, fixed front wheel, and Zip fold design that is 25% smaller than predecessors.',
    specs: {
      power: 'Electric Speed Dial Control',
      motor: 'Single 230W Low-Noise Calibrated Motor',
      battery: '24V 250Wh Click & Go Lithium (36 Hole)',
      weight: '9.8 kg (Without Battery)',
      wheels: '3-Wheel Fixed Front Geometry',
      foldSize: '70cm x 47cm x 42cm',
      brakes: 'Controlled Speed Descent',
      warranty: '3-Year Australian Warranty'
    },
    images: [
      '/images/products/mgi-zip-x1-electric-golf-buggy/main.webp',
      '/images/products/mgi-zip-x1-electric-golf-buggy/gallery-2.webp',
      '/images/products/mgi-zip-x1-electric-golf-buggy/gallery-3.webp',
      '/images/products/mgi-zip-x1-electric-golf-buggy/gallery-4.webp',
      '/images/products/mgi-zip-x1-electric-golf-buggy/gallery-5.webp'
    ]
  },
  {
    slug: 'mgi-zip-x3-electric-golf-buggy',
    name: 'MGI Zip X3 36-Hole Electric Golf Buggy',
    brand: 'mgi',
    brandName: 'MGI',
    category: 'electric-golf-buggies',
    categoryPath: '/electric-golf-buggies/',
    price: 1299,
    condition: 'New',
    badge: 'Popular Retail Pick',
    featured: false,
    rating: 4.8,
    reviewCount: 112,
    power: 'Electric',
    wheels: '3-wheel',
    batteryRange: '36 hole',
    weightCategory: '10–13 kg',
    weightKg: 10.3,
    foldSize: 'Compact / flat-fold',
    seats: 'Walk-behind',
    primaryKeyword: 'mgi zip x3 electric golf buggy',
    shortDescription: 'Features controlled distance function, swivelling lockable front wheel, digital odometer, and 36-hole 24V lithium pack.',
    description: 'The MGI Zip X3 enhances your walking round with Controlled Distance Function (send your buggy 5 to 60 metres ahead), swivelling front wheel for 360-degree fairway manoeuvrability, and a full-colour digital display.',
    specs: {
      power: 'Digital Display with Distance Presets',
      motor: '230W Whisper-Quiet AC Electric Motor',
      battery: '24V 250Wh Lithium Battery System',
      weight: '10.3 kg',
      wheels: 'Swivelling & Lockable Front Wheel',
      foldSize: '70cm x 47cm x 42cm',
      brakes: 'Automatic Slope Control',
      warranty: '3-Year Australian Warranty'
    },
    images: [
      '/images/products/mgi-zip-x3-electric-golf-buggy/main.webp',
      '/images/products/mgi-zip-x3-electric-golf-buggy/gallery-2.webp',
      '/images/products/mgi-zip-x3-electric-golf-buggy/gallery-3.webp',
      '/images/products/mgi-zip-x3-electric-golf-buggy/gallery-4.webp',
      '/images/products/mgi-zip-x3-electric-golf-buggy/gallery-5.webp',
      '/images/products/mgi-zip-x3-electric-golf-buggy/gallery-6.webp',
      '/images/products/mgi-zip-x3-electric-golf-buggy/gallery-7.webp'
    ]
  },
  {
    slug: 'mgi-zip-x5-electric-golf-buggy',
    name: 'MGI Zip X5 Downhill Braking Electric Golf Buggy',
    brand: 'mgi',
    brandName: 'MGI',
    category: 'electric-golf-buggies',
    categoryPath: '/electric-golf-buggies/',
    price: 1499,
    condition: 'New',
    badge: 'Downhill DHC',
    featured: false,
    rating: 4.9,
    reviewCount: 88,
    power: 'Electric',
    wheels: '3-wheel',
    batteryRange: '36 hole',
    weightCategory: '10–13 kg',
    weightKg: 10.5,
    foldSize: 'Compact / flat-fold',
    seats: 'Walk-behind',
    primaryKeyword: 'mgi zip x5 downhill brake golf buggy',
    shortDescription: 'Top-of-the-line walk-behind model featuring automatic Downhill Speed Control and Electronic Park Brake for effortless hill walking.',
    description: 'The MGI Zip X5 is designed for hilly golf courses. Features Electronic Park Brake (locks buggy on any incline at the touch of a button) and automatic Downhill Speed Control that maintains a constant walking pace down steep descents.',
    specs: {
      power: 'Digital Console with Electronic Park Brake',
      motor: '230W Calibrated Motor with DHC System',
      battery: '24V 250Wh Lithium Battery',
      weight: '10.5 kg',
      wheels: 'All-Terrain Low Profile Rear Tyres',
      foldSize: '70cm x 47cm x 42cm',
      brakes: 'Downhill Speed Regulation & Electronic Park Brake',
      warranty: '3-Year Australian Warranty'
    },
    images: [
      '/images/products/mgi-zip-x5-electric-golf-buggy/main.webp',
      '/images/products/mgi-zip-x5-electric-golf-buggy/gallery-2.webp',
      '/images/products/mgi-zip-x5-electric-golf-buggy/gallery-3.webp',
      '/images/products/mgi-zip-x5-electric-golf-buggy/gallery-4.webp',
      '/images/products/mgi-zip-x5-electric-golf-buggy/gallery-5.webp',
      '/images/products/mgi-zip-x5-electric-golf-buggy/gallery-6.webp',
      '/images/products/mgi-zip-x5-electric-golf-buggy/gallery-7.webp'
    ]
  },
  {
    slug: 'motocaddy-m1-dhc-electric-golf-buggy',
    name: 'Motocaddy M1 DHC Electric Golf Buggy',
    brand: 'motocaddy',
    brandName: 'Motocaddy',
    category: 'electric-golf-buggies',
    categoryPath: '/electric-golf-buggies/',
    price: 1299,
    condition: 'New',
    badge: 'Downhill Control',
    featured: false,
    rating: 4.8,
    reviewCount: 64,
    power: 'Electric',
    wheels: '3-wheel',
    batteryRange: '36 hole',
    weightCategory: 'Under 10 kg',
    weightKg: 9.9,
    foldSize: 'Compact / flat-fold',
    seats: 'Walk-behind',
    primaryKeyword: 'motocaddy m1 dhc electric golf buggy',
    shortDescription: 'Ultra-compact folding motorized trolley with Downhill Control, electronic parking brake, and 9 speed settings.',
    description: 'The Motocaddy M1 DHC adds automatic downhill braking, electronic parking brake, and all-terrain DHC wheels to the world\'s simplest compact-folding electric golf buggy.',
    specs: {
      power: '9-Speed Settings with Speed Indicator',
      motor: 'High Power 28V 230W DHC System',
      battery: '28.8V Ultra Lithium 36-Hole Battery',
      weight: '9.9 kg',
      wheels: 'Inverting All-Terrain DHC Wheels',
      foldSize: '65cm x 47cm x 41cm',
      brakes: 'Automatic Downhill Brake & Parking Brake',
      warranty: '2-Year Buggy / 5-Year Battery Warranty'
    },
    images: [
      '/images/products/motocaddy-m1-dhc-electric-golf-buggy/main.webp',
      '/images/products/motocaddy-m1-dhc-electric-golf-buggy/gallery-2.webp',
      '/images/products/motocaddy-m1-dhc-electric-golf-buggy/gallery-3.webp'
    ]
  },
  {
    slug: 'powakaddy-ct6-electric-golf-buggy',
    name: 'PowaKaddy CT6 Compact Electric Golf Buggy',
    brand: 'powakaddy',
    brandName: 'PowaKaddy',
    category: 'electric-golf-buggies',
    categoryPath: '/electric-golf-buggies/',
    price: 1199,
    condition: 'New',
    badge: 'Ultra-Compact Fold',
    featured: false,
    rating: 4.8,
    reviewCount: 47,
    power: 'Electric',
    wheels: '3-wheel',
    batteryRange: '36 hole',
    weightCategory: 'Under 10 kg',
    weightKg: 9.9,
    foldSize: 'Compact / flat-fold',
    seats: 'Walk-behind',
    primaryKeyword: 'powakaddy ct6 electric golf buggy',
    shortDescription: 'World\'s smallest ultra-compact electric trolley with 2.8" full colour widescreen display and 30V Plug \'n\' Play lithium battery.',
    description: 'The PowaKaddy CT6 folds 35% smaller than its nearest competitor with a Simple-2-Fold system, whisper-quiet 30V 230W motor, and automatic distance function (15, 30, 45 yards).',
    specs: {
      power: '2.8" OCA Mid-Size Full Colour Display',
      motor: '30V 230W High Performance Motor',
      battery: 'Plug \'n\' Play 30V 220Wh Lithium',
      weight: '9.9 kg',
      wheels: 'Metallic Low-Profile Sports Wheels',
      foldSize: '51cm x 42cm x 37cm',
      brakes: 'Standard Electric Brake',
      warranty: '2-Year Warranty'
    },
    images: [
      '/images/products/powakaddy-ct6-electric-golf-buggy/main.webp',
      '/images/products/powakaddy-ct6-electric-golf-buggy/gallery-2.webp',
      '/images/products/powakaddy-ct6-electric-golf-buggy/gallery-3.webp',
      '/images/products/powakaddy-ct6-electric-golf-buggy/gallery-4.webp'
    ]
  },

  // ==========================================
  // 3. GPS & FOLLOW / SMART GOLF BUGGIES
  // ==========================================
  {
    slug: 'mgi-ai-navigator-gps-plus-electric-golf-buggy',
    name: 'MGI Ai Navigator GPS+ Electric Golf Buggy',
    brand: 'mgi',
    brandName: 'MGI',
    category: 'gps-follow-buggies',
    categoryPath: '/gps-follow-buggies/',
    price: 2422,
    condition: 'New',
    badge: 'Built-in GPS Touchscreen',
    featured: true,
    rating: 5.0,
    reviewCount: 42,
    power: 'Follow / GPS',
    wheels: '4-wheel',
    batteryRange: '36 hole',
    weightCategory: '10–13 kg',
    weightKg: 13.5,
    foldSize: 'Compact / flat-fold',
    seats: 'Walk-behind',
    primaryKeyword: 'mgi ai navigator gps plus golf buggy',
    shortDescription: 'Integrated 4" full-colour high-resolution GPS touchscreen with 40,000+ preloaded Australian & international courses.',
    description: 'The MGI Ai Navigator GPS+ is the world\'s most technologically advanced golf buggy. Features an integrated 4-inch full-colour touchscreen GPS with 40,000+ courses worldwide, interactive hole maps, shot distance measuring, full directional remote control, and patented gyroscope straight-tracking.',
    specs: {
      power: 'Wireless Handset + Integrated 4" GPS Touchscreen',
      motor: 'Twin 230W Calibrated Brushless Drive',
      battery: '24V 380Wh Click & Go Lithium',
      weight: '13.5 kg',
      wheels: 'All-Terrain 4-Wheel Set',
      foldSize: '70cm x 47cm x 42cm',
      brakes: 'Downhill Speed Regulation & Park Brake',
      warranty: '3-Year Australian Warranty'
    },
    images: [
      '/images/products/mgi-ai-navigator-gps-plus-electric-golf-buggy/main.webp',
      '/images/products/mgi-ai-navigator-gps-plus-electric-golf-buggy/gallery-2.webp',
      '/images/products/mgi-ai-navigator-gps-plus-electric-golf-buggy/gallery-3.webp',
      '/images/products/mgi-ai-navigator-gps-plus-electric-golf-buggy/gallery-4.webp',
      '/images/products/mgi-ai-navigator-gps-plus-electric-golf-buggy/gallery-5.webp',
      '/images/products/mgi-ai-navigator-gps-plus-electric-golf-buggy/gallery-6.webp',
      '/images/products/mgi-ai-navigator-gps-plus-electric-golf-buggy/gallery-7.webp',
      '/images/products/mgi-ai-navigator-gps-plus-electric-golf-buggy/gallery-8.webp',
      '/images/products/mgi-ai-navigator-gps-plus-electric-golf-buggy/gallery-9.webp'
    ]
  },
  {
    slug: 'mgi-ai-navigator-halo-flagship-buggy',
    name: 'MGI Ai Navigator Halo Flagship Electric Buggy',
    brand: 'mgi',
    brandName: 'MGI',
    category: 'gps-follow-buggies',
    categoryPath: '/gps-follow-buggies/',
    price: 2762,
    condition: 'New',
    badge: 'Flagship Halo',
    featured: false,
    rating: 5.0,
    reviewCount: 29,
    power: 'Follow / GPS',
    wheels: '4-wheel',
    batteryRange: '36 hole',
    weightCategory: '10–13 kg',
    weightKg: 13.8,
    foldSize: 'Compact / flat-fold',
    seats: 'Walk-behind',
    primaryKeyword: 'mgi ai navigator halo flagship buggy',
    shortDescription: 'MGI\'s flagship masterpiece featuring full-colour touchscreen, cellular connectivity, hazard tracking, and bespoke champagne gold accents.',
    description: 'The ultimate expression of MGI engineering. Features full cellular IoT connectivity for automated course updates, real-time hazard mapping, 4" touchscreen GPS, and precision remote navigation.',
    specs: {
      power: 'Connected Touchscreen GPS & Precision Handset',
      motor: 'Twin High-Torque Calibrated Brushless Motors',
      battery: '24V 380Wh High-Density Lithium',
      weight: '13.8 kg',
      wheels: 'Halo Edition Wide All-Terrain Wheels',
      foldSize: '70cm x 47cm x 42cm',
      brakes: 'Dynamic Slope Braking & Auto Park',
      warranty: '3-Year VIP Australian Warranty'
    },
    images: [
      '/images/products/mgi-ai-navigator-halo-flagship-buggy/main.webp',
      '/images/products/mgi-ai-navigator-halo-flagship-buggy/gallery-2.webp',
      '/images/products/mgi-ai-navigator-halo-flagship-buggy/gallery-3.webp',
      '/images/products/mgi-ai-navigator-halo-flagship-buggy/gallery-4.webp',
      '/images/products/mgi-ai-navigator-halo-flagship-buggy/gallery-5.webp',
      '/images/products/mgi-ai-navigator-halo-flagship-buggy/gallery-6.webp',
      '/images/products/mgi-ai-navigator-halo-flagship-buggy/gallery-7.webp',
      '/images/products/mgi-ai-navigator-halo-flagship-buggy/gallery-8.webp',
      '/images/products/mgi-ai-navigator-halo-flagship-buggy/gallery-9.webp'
    ]
  },
  {
    slug: 'stewart-golf-q-follow-electric-buggy',
    name: 'Stewart Golf Q Follow Autonomous Electric Buggy',
    brand: 'stewart-golf',
    brandName: 'Stewart Golf',
    category: 'gps-follow-buggies',
    categoryPath: '/gps-follow-buggies/',
    price: 3290,
    condition: 'New',
    badge: 'True Auto-Follow',
    featured: true,
    rating: 4.9,
    reviewCount: 37,
    power: 'Follow / GPS',
    wheels: '4-wheel',
    batteryRange: '36 hole',
    weightCategory: '13 kg+',
    weightKg: 14.1,
    foldSize: 'Compact / flat-fold',
    seats: 'Walk-behind',
    primaryKeyword: 'stewart golf q follow electric buggy',
    shortDescription: 'World-renowned British autonomous follow-me golf buggy with 7th-generation follow system, honeycomb composite chassis, and 36-hole SmartPower lithium.',
    description: 'Walk completely hands-free. The Stewart Golf Q Follow uses Seventh-Generation Follow Technology with a Bluetooth tracking handset. Simply clip the handset to your belt and the Q Follow tracks your walking path automatically.',
    specs: {
      power: 'Seventh-Gen Autonomous Follow System',
      motor: 'Twin British Dual-Drive 24V Motors',
      battery: 'SmartPower 384Wh 36-Hole Lithium Pack',
      weight: '14.1 kg',
      wheels: 'Monocoque Honeycomb Composite Frame',
      foldSize: '54.5cm x 60cm x 31.8cm',
      brakes: 'Active Downhill Braking & Dual Electronic Brakes',
      warranty: '2-Year Australian Replacement Warranty'
    },
    images: [
      '/images/products/stewart-golf-q-follow-electric-buggy/main.webp',
      '/images/products/stewart-golf-q-follow-electric-buggy/gallery-2.webp',
      '/images/products/stewart-golf-q-follow-electric-buggy/gallery-3.webp',
      '/images/products/stewart-golf-q-follow-electric-buggy/gallery-4.webp'
    ]
  },
  {
    slug: 'alphard-club-booster-v2-pro-conversion-kit',
    name: 'Alphard Club Booster V2Pro Electric Conversion Kit',
    brand: 'alphard',
    brandName: 'Alphard Golf',
    category: 'conversion-kits',
    categoryPath: '/conversion-kits/',
    price: 1349,
    condition: 'New',
    badge: 'Converts Any Push Buggy',
    featured: false,
    rating: 4.9,
    reviewCount: 110,
    power: 'Remote control',
    wheels: '4-wheel',
    batteryRange: '36 hole',
    weightCategory: '10–13 kg',
    weightKg: 10.2,
    foldSize: 'Standard',
    seats: 'Walk-behind',
    primaryKeyword: 'alphard club booster v2pro conversion kit',
    shortDescription: 'Converts your existing Clicgear, Rovic, Sun Mountain, or Bag Boy manual push buggy into an all-terrain remote control electric trolley.',
    description: 'The Alphard Club Booster V2Pro replaces the rear axle of almost any manual push buggy, instantly turning it into a dual-motor remote-control electric buggy. Features dual brushless hub motors, electronic parking brake, cruise control, and 36-hole lithium battery.',
    specs: {
      power: 'Wireless Remote Handset Conversion Unit',
      motor: 'Twin Direct Drive Brushless Hub Motors',
      battery: '36V 5.2Ah Quick-Swap Lithium Pack',
      weight: '10.2 kg',
      wheels: 'Wide All-Terrain Wheel Set',
      foldSize: 'Axle Mounts to Cart Fold Geometry',
      brakes: 'Electronic Slope Brake & Hill Hold',
      warranty: '2-Year Manufacturer Warranty'
    },
    images: [
      '/images/products/alphard-club-booster-v2-pro-conversion-kit/main.webp',
      '/images/products/alphard-club-booster-v2-pro-conversion-kit/gallery-2.webp',
      '/images/products/alphard-club-booster-v2-pro-conversion-kit/gallery-3.webp'
    ]
  },

  // ==========================================
  // 4. MANUAL PUSH & PULL GOLF BUGGIES ($450+ FLOOR)
  // ==========================================
  {
    slug: 'clicgear-model-4-5-push-golf-buggy',
    name: 'Clicgear Model 4.5 3-Wheel Push Golf Buggy',
    brand: 'clicgear',
    brandName: 'Clicgear',
    category: 'push-pull-golf-buggies',
    categoryPath: '/push-pull-golf-buggies/',
    price: 549,
    condition: 'New',
    badge: 'Worldwide Benchmark',
    featured: true,
    rating: 5.0,
    reviewCount: 195,
    power: 'Manual push',
    wheels: '3-wheel',
    batteryRange: 'Manual',
    weightCategory: 'Under 10 kg',
    weightKg: 8.4,
    foldSize: 'Compact / flat-fold',
    seats: 'Walk-behind',
    primaryKeyword: 'clicgear model 4.5 push golf buggy',
    shortDescription: 'The global standard in manual 3-wheel golf push buggies. Heavy-duty aircraft aluminium tubing, maintenance-free airless tyres, and massive storage console.',
    description: 'The Clicgear Model 4.5 is the most durable, reliable 3-wheel manual push cart ever made. Features an adjustable silicone bag strap system, independent front wheel alignment, handle-mounted handbrake, scorecard console, and umbrella mount.',
    specs: {
      power: 'Manual Push (Gliding Ball Bearings)',
      motor: 'Manual Mechanical Glide',
      battery: 'None Required',
      weight: '8.4 kg',
      wheels: '3-Wheel Foam-Filled Airless Tyres',
      foldSize: '60cm x 38cm x 33cm (Ultra-Compact Cube Fold)',
      brakes: 'Positive Lock Handle Brake',
      warranty: '3-Year Australian Guarantee'
    },
    images: [
      '/images/products/clicgear-model-4-5-push-golf-buggy/main.webp',
      '/images/products/clicgear-model-4-5-push-golf-buggy/gallery-2.webp'
    ]
  },
  {
    slug: 'big-max-blade-ip2-flat-fold-golf-buggy',
    name: 'Big Max Blade IP 2 Ultra-Flat Push Golf Buggy',
    brand: 'big-max',
    brandName: 'Big Max',
    category: 'push-pull-golf-buggies',
    categoryPath: '/push-pull-golf-buggies/',
    price: 580,
    condition: 'New',
    badge: 'Thinnest Fold',
    featured: false,
    rating: 4.9,
    reviewCount: 48,
    power: 'Manual push',
    wheels: '3-wheel',
    batteryRange: 'Manual',
    weightCategory: 'Under 10 kg',
    weightKg: 6.5,
    foldSize: 'Compact / flat-fold',
    seats: 'Walk-behind',
    primaryKeyword: 'big max blade ip2 flat fold golf buggy',
    shortDescription: 'The world\'s flattest folding 3-wheel golf trolley, collapsing to an incredible 12.5 cm depth for easy boot and locker storage.',
    description: 'Engineered in Austria, the Big Max Blade IP 2 folds completely flat in seconds. Features Quick-Fold technology, dual footbrakes, integrated scorecard compartment, and aircraft-grade featherweight aluminium.',
    specs: {
      power: 'Manual Push',
      motor: 'Manual',
      battery: 'None',
      weight: '6.5 kg',
      wheels: '3-Wheel Low Profile Ball-Bearing Tyres',
      foldSize: '88cm x 62cm x 12.5cm (Ultra-Flat)',
      brakes: 'Dual Footbrakes',
      warranty: '5-Year Manufacturer Warranty'
    },
    images: [
      'https://images.unsplash.com/photo-1592919505780-303950717480?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1593111774642-a1548e64c5d5?auto=format&fit=crop&w=1200&q=80'
    ]
  },
  {
    slug: 'clicgear-rovic-rv1s-swivel-push-golf-buggy',
    name: 'Clicgear Rovic RV1S Swivel Front Wheel Push Buggy',
    brand: 'clicgear',
    brandName: 'Clicgear (Rovic)',
    category: 'push-pull-golf-buggies',
    categoryPath: '/push-pull-golf-buggies/',
    price: 449,
    condition: 'New',
    badge: 'Swivel Wheel',
    featured: false,
    rating: 4.8,
    reviewCount: 62,
    power: 'Manual push',
    wheels: '3-wheel',
    batteryRange: 'Manual',
    weightCategory: 'Under 10 kg',
    weightKg: 7.6,
    foldSize: 'Compact / flat-fold',
    seats: 'Walk-behind',
    primaryKeyword: 'clicgear rovic rv1s swivel push golf buggy',
    shortDescription: '360-degree front swivelling wheel for effortless steering on tight tee boxes and around green complexes.',
    description: 'The Rovic RV1S by Clicgear provides full 360-degree swivel front-wheel manoeuvrability. The front wheel can be locked straight with a handlebar lever for long fairway pushes.',
    specs: {
      power: 'Manual Push with 360-Degree Swivel',
      motor: 'Manual',
      battery: 'None',
      weight: '7.6 kg',
      wheels: '3-Wheel Swivel Geometry',
      foldSize: '61cm x 38cm x 33cm',
      brakes: 'Handlebar Brake Lever',
      warranty: '2-Year Australian Warranty'
    },
    images: [
      '/images/products/clicgear-rovic-rv1s-swivel-push-golf-buggy/main.webp',
      '/images/products/clicgear-rovic-rv1s-swivel-push-golf-buggy/gallery-2.webp'
    ]
  },

  // ==========================================
  // 5. RIDE-ON GOLF CARTS (2-6 SEAT LUXURY & RESORT)
  // ==========================================
  {
    slug: 'cougar-2-seater-electric-golf-cart',
    name: 'Cougar 2-Seater Electric Golf Cart',
    brand: 'cougar',
    brandName: 'Cougar',
    category: 'luxury-golf-carts',
    categoryPath: '/luxury-golf-carts/',
    price: 7450,
    condition: 'New',
    badge: 'Best Value New Cart',
    featured: true,
    rating: 4.8,
    reviewCount: 26,
    power: 'Electric',
    wheels: '4-wheel',
    batteryRange: '36 hole',
    weightCategory: '13 kg+',
    weightKg: 280,
    foldSize: 'Standard',
    seats: '2-Passenger Seating',
    primaryKeyword: 'cougar 2 seater electric golf cart',
    shortDescription: 'Australia\'s most affordable new 2-seater golf cart with 48V electric motor, split windscreen, bag holder, and turnkey charger.',
    description: 'Recognized by Inside Golf as Australia\'s best-value new golf cart. The Cougar 2-Seater comes standard with 48V electric drivetrain, Curtis controller, heavy-duty suspension, dual golf bag holders, split folding windscreen, and fast onboard charger.',
    specs: {
      seating: '2-Passenger Forward-Facing',
      motor: '48V 3.8kW AC Electric Motor',
      battery: '48V Deep-Cycle Battery Pack (Lithium Upgrade Available)',
      range: '60+ km Per Charge (36+ Holes)',
      topSpeed: '24 km/h (Golf Regulated)',
      brakes: 'Mechanical Drum Brakes with Park Lock',
      payloadCapacity: '360 kg Payload',
      warranty: '2-Year Comprehensive Warranty'
    },
    images: [
      'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1594495894542-a46cc73e081a?auto=format&fit=crop&w=1200&q=80'
    ]
  },
  {
    slug: 'ecar-lithium-a2-2-seater-golf-cart',
    name: 'ECAR Lithium A2 2-Seater Golf Cart',
    brand: 'ecar',
    brandName: 'ECAR',
    category: 'luxury-golf-carts',
    categoryPath: '/luxury-golf-carts/',
    price: 10990,
    condition: 'New',
    badge: 'Lithium Standard',
    featured: true,
    rating: 4.9,
    reviewCount: 41,
    power: 'Electric',
    wheels: '4-wheel',
    batteryRange: '36 hole',
    weightCategory: '13 kg+',
    weightKg: 320,
    foldSize: 'Standard',
    seats: '2-Passenger Seating',
    primaryKeyword: 'ecar lithium a2 golf cart',
    shortDescription: 'Turnkey commercial-grade 2-seater cart with zero-maintenance LiFePO4 lithium pack, Toyota AC controller, and automotive lighting.',
    description: 'The ECAR Lithium A2 is the premier choice for Australian golf clubs, private estate owners, and gated communities. Powered by a maintenance-free 48V 105Ah LiFePO4 lithium battery and advanced Toyota AC controller.',
    specs: {
      seating: '2-Passenger Premium Contour Marine Vinyl',
      motor: '48V 4.0kW High-Efficiency AC Motor',
      battery: '48V 105Ah LiFePO4 Lithium (5-Year Warranty)',
      range: '80+ km Per Charge',
      topSpeed: '25 km/h',
      brakes: 'Four-Wheel Hydraulic Disc Brakes & Auto Park',
      payloadCapacity: '400 kg',
      warranty: '5-Year Battery / 3-Year Chassis Warranty'
    },
    images: [
      'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1594495894542-a46cc73e081a?auto=format&fit=crop&w=1200&q=80'
    ]
  },
  {
    slug: 'rippa-4-seat-electric-golf-cart',
    name: 'Rippa 4-Seat Electric Golf Cart Australia',
    brand: 'rippa',
    brandName: 'Rippa',
    category: 'luxury-golf-carts',
    categoryPath: '/luxury-golf-carts/',
    price: 12990,
    condition: 'New',
    badge: '4-Passenger Value',
    featured: false,
    rating: 4.8,
    reviewCount: 33,
    power: 'Electric',
    wheels: '4-wheel',
    batteryRange: '36 hole',
    weightCategory: '13 kg+',
    weightKg: 360,
    foldSize: 'Standard',
    seats: '4-Passenger Seating (2+2)',
    primaryKeyword: 'rippa 4 seat electric golf cart',
    shortDescription: 'Family and resort 4-seater with fold-down rear utility cargo deck, full LED lighting, and long-range lithium pack.',
    description: 'The Rippa 4-Seat Electric Cart is ideal for golf resorts, lifestyle villages, and private properties. Features 2 forward seats and 2 rear-facing seats that fold down into a heavy-duty flat cargo deck.',
    specs: {
      seating: '4-Passenger (2+2 Flip-Flop Cargo Seat)',
      motor: '48V 4.0kW AC Motor',
      battery: '48V 100Ah Lithium LiFePO4',
      range: '75+ km Per Charge',
      topSpeed: '25 km/h (Conditional Road Compliant)',
      brakes: 'Hydraulic 4-Wheel Disc Brakes',
      payloadCapacity: '450 kg',
      warranty: '3-Year Australian Warranty'
    },
    images: [
      'https://images.unsplash.com/photo-1594495894542-a46cc73e081a?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?auto=format&fit=crop&w=1200&q=80'
    ]
  },
  {
    slug: 'ecar-lithium-a4-4-seater-golf-cart',
    name: 'ECAR Lithium A4 4-Seater Golf Cart',
    brand: 'ecar',
    brandName: 'ECAR',
    category: 'luxury-golf-carts',
    categoryPath: '/luxury-golf-carts/',
    price: 13990,
    condition: 'New',
    badge: '4-Seat Benchmark',
    featured: true,
    rating: 4.9,
    reviewCount: 56,
    power: 'Electric',
    wheels: '4-wheel',
    batteryRange: '36 hole',
    weightCategory: '13 kg+',
    weightKg: 380,
    foldSize: 'Standard',
    seats: '4-Passenger Seating',
    primaryKeyword: 'ecar lithium a4 4 seater golf cart',
    shortDescription: 'Australia\'s best-value 4-seater with 48V LiFePO4 lithium battery, extended roof, and premium marine upholstery.',
    description: 'The ECAR Lithium A4 delivers luxury personal mobility for 4 adults. Equipped with an extended colour-matched hardtop roof, 10" alloy wheels, rear grab bar, split windscreen, and 48V 105Ah lithium pack.',
    specs: {
      seating: '4-Passenger Forward & Rear Seats',
      motor: '48V 4.0kW Toyota AC System',
      battery: '48V 105Ah LiFePO4 Lithium Battery',
      range: '80 km Per Charge',
      topSpeed: '25 km/h',
      brakes: 'Hydraulic Disc Brakes',
      payloadCapacity: '450 kg',
      warranty: '5-Year Lithium / 3-Year Vehicle Warranty'
    },
    images: [
      'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1594495894542-a46cc73e081a?auto=format&fit=crop&w=1200&q=80'
    ]
  },
  {
    slug: 'ecar-lithium-magnum-4lr-lifted-golf-cart',
    name: 'ECAR Lithium Magnum 4LR Lifted 4x4 Off-Road Cart',
    brand: 'ecar',
    brandName: 'ECAR',
    category: 'luxury-golf-carts',
    categoryPath: '/luxury-golf-carts/',
    price: 16990,
    condition: 'New',
    badge: 'Lifted All-Terrain',
    featured: false,
    rating: 4.9,
    reviewCount: 29,
    power: 'Electric',
    wheels: '4-wheel',
    batteryRange: '36 hole',
    weightCategory: '13 kg+',
    weightKg: 420,
    foldSize: 'Standard',
    seats: '4-Passenger Seating',
    primaryKeyword: 'ecar magnum 4lr lifted golf cart',
    shortDescription: 'High-riding lifted all-terrain cruiser with 12" knobby tyres, heavy-duty suspension, bull bar, and 48V lithium power.',
    description: 'Designed for rural acreage, undulating farm trails, and rugged coastal properties. Features 6" suspension lift kit, 23" all-terrain knobby tyres, steel front brush guard, and 48V 105Ah LiFePO4 battery.',
    specs: {
      seating: '4-Passenger Elevated Seats',
      motor: '48V 5.0kW High-Torque AC Motor',
      battery: '48V 105Ah Deep-Cycle Lithium',
      range: '70+ km (Rough Terrain)',
      topSpeed: '32 km/h',
      groundClearance: '210 mm Ground Clearance',
      brakes: '4-Wheel Hydraulic Disc Brakes',
      warranty: '5-Year Battery / 3-Year Chassis'
    },
    images: [
      'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?auto=format&fit=crop&w=1200&q=80'
    ]
  },
  {
    slug: 'tomberlin-e-merge-ss-4-seat-saloon-cart',
    name: 'Tomberlin E-Merge SS 4-Seat Luxury Saloon Cart',
    brand: 'tomberlin',
    brandName: 'Tomberlin',
    category: 'luxury-golf-carts',
    categoryPath: '/luxury-golf-carts/',
    price: 27990,
    condition: 'New',
    badge: 'Resort Flagship',
    featured: true,
    rating: 5.0,
    reviewCount: 21,
    power: 'Electric',
    wheels: '4-wheel',
    batteryRange: '36 hole',
    weightCategory: '13 kg+',
    weightKg: 460,
    foldSize: 'Standard',
    seats: '4-Passenger Seating',
    primaryKeyword: 'tomberlin e merge ss 4 seat saloon',
    shortDescription: 'Automotive luxury featuring diamond double-stitched leather upholstery, 7" digital LCD dash, rearview camera, and 4-wheel disc brakes.',
    description: 'The Tomberlin E-Merge SS (Super Sport) Saloon is the pinnacle of luxury estate mobility. Fitted with 3-point seatbelts, illuminated cupholders, Bluetooth sound system, and electric power steering.',
    specs: {
      seating: '4-Passenger Diamond Stitched Luxury Seats',
      motor: '48V 5.0kW AC High Performance Motor',
      battery: '48V 105Ah Premium Lithium LiFePO4',
      range: '90+ km Per Charge',
      topSpeed: '38 km/h (Conditional Road Compliant)',
      brakes: '4-Wheel Hydraulic Disc Brakes & Electric Power Steering',
      warranty: '5-Year Factory Warranty'
    },
    images: [
      'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1594495894542-a46cc73e081a?auto=format&fit=crop&w=1200&q=80'
    ]
  },
  {
    slug: 'garia-lithium-luxury-golf-cart',
    name: 'Garia Lithium Luxury Golf Cart (Danish Handcrafted)',
    brand: 'garia',
    brandName: 'Garia',
    category: 'luxury-golf-carts',
    categoryPath: '/luxury-golf-carts/',
    price: 62500,
    condition: 'New',
    badge: 'The Rolls-Royce of Carts',
    featured: false,
    rating: 5.0,
    reviewCount: 14,
    power: 'Electric',
    wheels: '4-wheel',
    batteryRange: '36 hole',
    weightCategory: '13 kg+',
    weightKg: 520,
    foldSize: 'Standard',
    seats: '2-Passenger (Optional 2+2)',
    primaryKeyword: 'garia luxury golf cart australia',
    shortDescription: 'Handcrafted in Denmark. Automotive double wishbone suspension, carbon fibre roof, built-in refrigerator, and 10.1" touchscreen infotainment.',
    description: 'Regarded globally as "the Rolls-Royce of golf carts". Hand-built in Denmark with Formula 1 inspired double wishbone suspension, custom bridge-of-weir leather seats, built-in dashboard refrigerator, and 10.1" touchscreen.',
    specs: {
      seating: '2-Passenger Hand-Stitched Scottish Leather',
      motor: '48V 3.0kW Ultra-Quiet AC Drivetrain',
      battery: 'Samsung SDI Lithium High Capacity Pack',
      range: '95+ km Single Charge',
      topSpeed: '30 km/h (Road Registerable Ready)',
      brakes: 'Dual Circuit Hydraulic Disc Brakes',
      warranty: '3-Year Bespoke Manufacturer Warranty'
    },
    images: [
      'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1594495894542-a46cc73e081a?auto=format&fit=crop&w=1200&q=80'
    ]
  },

  // ==========================================
  // 6. OFF-ROAD & RECREATIONAL UTVS ($1,699 - $38,995)
  // ==========================================
  {
    slug: 'gmx-gkt150-dune-buggy',
    name: 'GMX GKT150 150cc 2-Seat Dune Buggy',
    brand: 'gmx',
    brandName: 'GMX',
    category: 'off-road-buggies',
    categoryPath: '/off-road-buggies/',
    price: 2999,
    condition: 'New',
    badge: 'Recreational Dune',
    featured: true,
    rating: 4.8,
    reviewCount: 38,
    power: 'Petrol',
    wheels: '4-wheel',
    batteryRange: 'Petrol Tank',
    weightCategory: '13 kg+',
    weightKg: 190,
    foldSize: 'Standard',
    seats: '2-Passenger Seating',
    primaryKeyword: 'gmx gkt150 dune buggy australia',
    shortDescription: '150cc 4-stroke petrol dune buggy with automatic CVT transmission, roll cage, dual bucket seats, and hydraulic disc brakes.',
    description: 'The GMX GKT150 is the ultimate weekend recreational buggy for dirt tracks, dunes, and farm paddocks. Powered by a reliable 150cc GY6 engine with electric start and reverse gear.',
    specs: {
      engine: '150cc 4-Stroke Air-Cooled Petrol Single Cylinder',
      transmission: 'Automatic CVT (Forward, Neutral, Reverse)',
      starter: 'Electric Push Button Start',
      topSpeed: '55 km/h',
      brakes: 'Front & Rear Hydraulic Disc Brakes',
      safety: 'Full Tubular Steel Roll Cage & 4-Point Harnesses',
      warranty: '12-Month Australian Parts Warranty'
    },
    images: [
      'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?auto=format&fit=crop&w=1200&q=80'
    ]
  },
  {
    slug: 'crossfire-blazer-200r-dune-buggy',
    name: 'Crossfire Blazer 200R Teen / Adult Off-Road Buggy',
    brand: 'crossfire',
    brandName: 'Crossfire',
    category: 'off-road-buggies',
    categoryPath: '/off-road-buggies/',
    price: 3199,
    condition: 'New',
    badge: 'Acreage Favourite',
    featured: false,
    rating: 4.9,
    reviewCount: 44,
    power: 'Petrol',
    wheels: '4-wheel',
    batteryRange: 'Petrol Tank',
    weightCategory: '13 kg+',
    weightKg: 175,
    foldSize: 'Standard',
    seats: '2-Passenger Seating',
    primaryKeyword: 'crossfire blazer 200r buggy',
    shortDescription: '200cc 4-stroke torque-converter dune buggy with dual A-arm suspension, LED headlights, and speed governor for teen safety.',
    description: 'The Crossfire Blazer 200R bridges teen and adult recreational off-roading. Built with dual A-arm front suspension, heavy-duty rear swingarm, and adjustable throttle limiter.',
    specs: {
      engine: '196cc 4-Stroke OHV Single Cylinder Engine',
      transmission: 'Torque Converter (Automatic CVT with Reverse)',
      topSpeed: '48 km/h (Speed Governor Adjustable)',
      brakes: 'Hydraulic Rear Disc Brake',
      payloadCapacity: '180 kg (2-Passenger)',
      warranty: '12-Month Factory Warranty'
    },
    images: [
      'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?auto=format&fit=crop&w=1200&q=80'
    ]
  },
  {
    slug: 'kayo-s350-side-by-side-utv',
    name: 'Kayo S350 2-Seat Side-by-Side UTV',
    brand: 'kayo',
    brandName: 'Kayo Moto',
    category: 'off-road-buggies',
    categoryPath: '/off-road-buggies/',
    price: 8999,
    condition: 'New',
    badge: 'Popular UTV Pick',
    featured: false,
    rating: 4.8,
    reviewCount: 28,
    power: 'Petrol',
    wheels: '4-wheel',
    batteryRange: 'Petrol Tank',
    weightCategory: '13 kg+',
    weightKg: 340,
    foldSize: 'Standard',
    seats: '2-Passenger Seating',
    primaryKeyword: 'kayo s350 side by side utv',
    shortDescription: '350cc fuel-injected recreation and light farm UTV with tipper cargo box, roof, windscreen, and tow hitch.',
    description: 'The Kayo S350 offers full UTV utility at under $9,000 AUD. Equipped with a responsive EFI engine, independent double wishbone suspension, tilting rear cargo bed, and 12-inch aluminium wheels.',
    specs: {
      engine: '350cc Liquid-Cooled 4-Stroke Electronic Fuel Injection (EFI)',
      transmission: 'Automatic CVT with High, Low, Neutral, Reverse',
      towingCapacity: '450 kg Tow Rating',
      brakes: '4-Wheel Hydraulic Disc Brakes',
      cargoBed: 'Rear Tilting Tipper Bed (150 kg Capacity)',
      warranty: '12-Month Parts & Labour Warranty'
    },
    images: [
      'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1594495894542-a46cc73e081a?auto=format&fit=crop&w=1200&q=80'
    ]
  },
  {
    slug: 'crossfire-400gt-4x4-farm-utv',
    name: 'Crossfire 400GT 4x4 Heavy-Duty Farm UTV',
    brand: 'crossfire',
    brandName: 'Crossfire',
    category: 'off-road-buggies',
    categoryPath: '/off-road-buggies/',
    price: 10999,
    condition: 'New',
    badge: 'Selectable 4WD',
    featured: true,
    rating: 4.9,
    reviewCount: 35,
    power: 'Petrol',
    wheels: '4-wheel',
    batteryRange: 'Petrol Tank',
    weightCategory: '13 kg+',
    weightKg: 520,
    foldSize: 'Standard',
    seats: '2-Passenger Seating',
    primaryKeyword: 'crossfire 400gt 4x4 farm utv',
    shortDescription: 'Selectable 2WD/4WD with front differential lock, electronic power steering, electric winch, and hydraulic tip tray.',
    description: 'A genuine workhorse for Australian rural properties and farms. Features selectable 4x4 with differential lock, 3,500lb electric front winch, tow hitch, and gas-assist tipping cargo bed.',
    specs: {
      engine: '400cc EFI Liquid-Cooled 4-Stroke Engine',
      driveSystem: 'Selectable 2WD / 4WD with Front Diff Lock',
      transmission: 'Automatic CVT (H/L/N/R/P)',
      winch: '3,500 lb Heavy-Duty Electric Winch',
      towingCapacity: '550 kg Tow Rating',
      warranty: '2-Year Australian Commercial Warranty'
    },
    images: [
      'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?auto=format&fit=crop&w=1200&q=80'
    ]
  },
  {
    slug: 'polaris-ranger-xp-1000-hd-utv',
    name: 'Polaris Ranger XP 1000 Heavy Duty Side-by-Side',
    brand: 'polaris',
    brandName: 'Polaris',
    category: 'off-road-buggies',
    categoryPath: '/off-road-buggies/',
    price: 38995,
    condition: 'New',
    badge: 'Heavy Duty UTV',
    featured: false,
    rating: 5.0,
    reviewCount: 19,
    power: 'Petrol',
    wheels: '4-wheel',
    batteryRange: 'Petrol Tank',
    weightCategory: '13 kg+',
    weightKg: 780,
    foldSize: 'Standard',
    seats: '3-Passenger Bench',
    primaryKeyword: 'polaris ranger xp 1000 australia',
    shortDescription: 'The undisputed heavy-duty king. 82 HP ProStar 1000cc engine, 1,134 kg towing capacity, and On-Demand True All-Wheel Drive.',
    description: 'Australia\'s premier side-by-side for heavy agricultural, commercial, and sporting estate transport. Powered by the legendary 999cc twin-cylinder ProStar engine with 13 inches of ground clearance.',
    specs: {
      engine: '999cc 4-Stroke DOHC Twin Cylinder (82 HP)',
      driveSystem: 'High Performance On-Demand True AWD/2WD/VersaTrac Turf Mode',
      payloadCapacity: '680 kg Payload Capacity',
      towingCapacity: '1,134 kg Tow Rating',
      groundClearance: '330 mm (13 in)',
      warranty: '2-Year Factory Warranty'
    },
    images: [
      'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?auto=format&fit=crop&w=1200&q=80'
    ]
  },

  // ==========================================
  // 7. KIDS & TEEN BUGGIES ($850+ FLOOR)
  // ==========================================
  {
    slug: 'electric-48v-kids-4x4-off-road-buggy',
    name: '48V Electric Kids 4x4 Off-Road Buggy',
    brand: 'buggy-shop-junior',
    brandName: 'The Buggy Shop Junior',
    category: 'kids-buggies',
    categoryPath: '/kids-buggies/',
    price: 1290,
    condition: 'New',
    badge: '48V Electric Kids',
    featured: true,
    rating: 4.9,
    reviewCount: 46,
    power: 'Electric',
    wheels: '4-wheel',
    batteryRange: '18 hole',
    weightCategory: '13 kg+',
    weightKg: 68,
    foldSize: 'Standard',
    seats: '2-Child Seating',
    primaryKeyword: 'kids electric buggy 48v australia',
    shortDescription: '48V 1000W brushless electric kids buggy with 3-speed parental lock, hydraulic rear disc brake, and full roll cage.',
    description: 'A genuine high-voltage electric buggy for kids aged 6-12. Features 48V 1000W brushless motor, key-switch parental speed control (10 km/h, 20 km/h, 32 km/h), leather bucket seats, and hydraulic brakes.',
    specs: {
      motor: '48V 1000W Brushless High-Torque Electric Motor',
      battery: '48V 20Ah Rechargeable Deep-Cycle Battery Pack',
      speedLimit: '3-Speed Key Lock (10 km/h, 20 km/h, 32 km/h)',
      safety: 'Full Roll Cage, 3-Point Harnesses, Remote Safety Kill Switch',
      payloadCapacity: '85 kg',
      warranty: '12-Month Australian Warranty'
    },
    images: [
      'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?auto=format&fit=crop&w=1200&q=80'
    ]
  },
  {
    slug: 'crossfire-90cc-twin-seat-kids-petrol-buggy',
    name: 'Crossfire 90cc Twin-Seat Petrol Kids Buggy',
    brand: 'crossfire',
    brandName: 'Crossfire',
    category: 'kids-buggies',
    categoryPath: '/kids-buggies/',
    price: 1890,
    condition: 'New',
    badge: '90cc Petrol Kids',
    featured: false,
    rating: 4.8,
    reviewCount: 31,
    power: 'Petrol',
    wheels: '4-wheel',
    batteryRange: 'Petrol Tank',
    weightCategory: '13 kg+',
    weightKg: 110,
    foldSize: 'Standard',
    seats: '2-Child Seating',
    primaryKeyword: 'kids 90cc petrol buggy australia',
    shortDescription: '90cc 4-stroke electric-start petrol buggy with automatic transmission, adjustable speed governor, and dual padded bucket seats.',
    description: 'Engineered for young riders taking their first steps in off-roading. Equipped with a reliable 90cc electric-start engine, full padded roll cage, throttle limiter, and rear disc brake.',
    specs: {
      engine: '90cc 4-Stroke Air-Cooled Petrol Engine',
      starter: 'Electric Key Start',
      transmission: 'Fully Automatic Single Speed',
      safety: 'Parental Throttle Limiter & Safety Flag Included',
      payloadCapacity: '95 kg',
      warranty: '12-Month Factory Warranty'
    },
    images: [
      'https://images.unsplash.com/photo-1518609878373-06d740f60d8b?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?auto=format&fit=crop&w=1200&q=80'
    ]
  },

  // ==========================================
  // 8. LITHIUM BATTERIES & CHARGERS
  // ==========================================
  {
    slug: 'mgi-24v-380wh-click-and-go-lithium-battery',
    name: 'MGI 24V 380Wh 36-Hole Click & Go Lithium Battery Pack',
    brand: 'mgi',
    brandName: 'MGI',
    category: 'batteries',
    categoryPath: '/batteries/',
    price: 499,
    condition: 'New',
    badge: 'Genuine OEM',
    featured: true,
    rating: 5.0,
    reviewCount: 142,
    power: 'Battery',
    wheels: 'Accessory',
    batteryRange: '36 hole',
    weightCategory: 'Under 10 kg',
    weightKg: 2.8,
    foldSize: 'Compact / flat-fold',
    seats: 'Part',
    primaryKeyword: 'mgi 24v lithium battery replacement price',
    shortDescription: 'Genuine OEM 24V 380Wh 36-hole lithium battery compatible with all MGI Zip and Ai series electric golf buggies.',
    description: 'Genuine factory replacement Click & Go 24V 380Wh lithium battery pack for MGI Zip Navigator, Zip X1, X3, X5, and Ai series. Delivers up to 36+ holes on a single charge with integrated Battery Management System (BMS).',
    specs: {
      voltage: '24V Direct Fit Click & Go System',
      capacity: '380Wh (36+ Holes Capacity)',
      chemistry: 'High-Density Lithium-Ion',
      weight: '2.8 kg',
      compatibility: 'All MGI Zip & MGI Ai Series Buggies',
      warranty: '2-Year Australian Replacement Warranty'
    },
    images: [
      'https://images.unsplash.com/photo-1593111774642-a1548e64c5d5?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1592919505780-303950717480?auto=format&fit=crop&w=1200&q=80'
    ]
  },
  {
    slug: 'giant-48v-90ah-golf-cart-drop-in-lithium-battery',
    name: 'GIANT 48V 90Ah Drop-In Golf Cart LiFePO4 Lithium Battery',
    brand: 'giant',
    brandName: 'GIANT Power',
    category: 'batteries',
    categoryPath: '/batteries/',
    price: 1479,
    condition: 'New',
    badge: 'Drop-In Cart Lithium',
    featured: false,
    rating: 4.9,
    reviewCount: 39,
    power: 'Battery',
    wheels: 'Accessory',
    batteryRange: '36 hole',
    weightCategory: '13 kg+',
    weightKg: 38,
    foldSize: 'Standard',
    seats: 'Part',
    primaryKeyword: '48v drop in lithium golf cart battery australia',
    shortDescription: 'Single-cased 48V 90Ah LiFePO4 lithium conversion unit replacing 6 or 8 heavy lead-acid batteries in Club Car, Yamaha, and E-Z-GO carts.',
    description: 'Transform your heavy lead-acid golf cart. Shed 130+ kg of weight and gain 80+ km of single-charge range with this single drop-in 48V 90Ah LiFePO4 battery with Bluetooth battery status app.',
    specs: {
      voltage: '48V Nominal (51.2V Actual)',
      capacity: '90Ah (4.6 kWh Usable Power)',
      cycleLife: '3,500+ Deep Discharge Cycles',
      weight: '38 kg (Saves 130kg+ over Lead Acid)',
      compatibility: 'Club Car, Yamaha, E-Z-GO, ECAR 48V Carts',
      warranty: '5-Year Australian Replacement Warranty'
    },
    images: [
      'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1594495894542-a46cc73e081a?auto=format&fit=crop&w=1200&q=80'
    ]
  },

  // ==========================================
  // 9. USED & EX-DEMO GOLF BUGGIES
  // ==========================================
  {
    slug: 'ex-demo-mgi-zip-navigator-at-remote-buggy',
    name: 'Ex-Demo MGI Zip Navigator AT Remote Buggy (Certified)',
    brand: 'mgi',
    brandName: 'MGI',
    category: 'used-golf-buggies',
    categoryPath: '/used-golf-buggies/',
    price: 1490,
    condition: 'Ex-Demo',
    badge: 'Certified Pre-Owned',
    featured: true,
    rating: 4.9,
    reviewCount: 18,
    power: 'Remote control',
    wheels: '4-wheel',
    batteryRange: '36 hole',
    weightCategory: '10–13 kg',
    weightKg: 13.0,
    foldSize: 'Compact / flat-fold',
    seats: 'Walk-behind',
    primaryKeyword: 'used mgi zip navigator for sale australia',
    shortDescription: 'Factory-inspected ex-showroom demonstration unit with tested 36-hole 24V lithium battery, remote handset, and 12-month warranty.',
    description: 'Save $600+ AUD on Australia\'s favourite remote buggy. Certified ex-demonstration unit thoroughly workshop-tested with brand-new tyres, fully health-tested 24V lithium battery, and 12-month dealer warranty.',
    specs: {
      condition: 'Grade A+ Ex-Showroom Demonstration',
      motor: 'Twin 230W Calibrated Motors',
      battery: 'Tested 24V 380Wh Lithium (98%+ Health)',
      remote: 'Included with USB Charging Cable',
      brakes: 'Downhill Speed Regulation',
      warranty: '12-Month Australian Warranty'
    },
    images: [
      'https://images.unsplash.com/photo-1535131749006-b7f58c99034b?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1593111774642-a1548e64c5d5?auto=format&fit=crop&w=1200&q=80'
    ]
  },
  {
    slug: 'ex-fleet-ezgo-rxv-48v-lithium-2-seat-cart',
    name: 'Ex-Fleet E-Z-GO RXV 48V Lithium 2-Seat Cart (Refurbished)',
    brand: 'ezgo',
    brandName: 'E-Z-GO',
    category: 'used-golf-buggies',
    categoryPath: '/used-golf-buggies/',
    price: 6490,
    condition: 'Used',
    badge: 'Ex-Fleet Value',
    featured: false,
    rating: 4.8,
    reviewCount: 15,
    power: 'Electric',
    wheels: '4-wheel',
    batteryRange: '36 hole',
    weightCategory: '13 kg+',
    weightKg: 290,
    foldSize: 'Standard',
    seats: '2-Passenger Seating',
    primaryKeyword: 'used ezgo rxv golf cart for sale melbourne brisbane',
    shortDescription: 'Ex-resort lease return with brand-new 48V lithium battery conversion, automatic park brake, and split windscreen.',
    description: 'Premium ex-lease resort cart rebuilt by our Queensland technical workshop. Fitted with a brand-new 48V drop-in lithium battery pack, automatic IntelliBrake park brake, split windscreen, and charger.',
    specs: {
      condition: 'Workshop Refurbished & Tested',
      motor: '48V AC Induction Motor',
      battery: 'Brand-New 48V Drop-In Lithium Pack',
      range: '70+ km Per Charge',
      brakes: 'Patented IntelliBrake Auto Park System',
      warranty: '12-Month Vehicle / 3-Year Battery Warranty'
    },
    images: [
      'https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1594495894542-a46cc73e081a?auto=format&fit=crop&w=1200&q=80'
    ]
  }
,
  {
    slug: 'mgi-zip-navigator-at-all-terrain-golf-buggy',
    name: 'MGI Zip Navigator AT All-Terrain Conversion Bundle',
    brand: 'mgi',
    brandName: 'MGI',
    category: 'conversion-kits',
    categoryPath: '/electric-golf-buggies/conversion-kits/',
    price: 1999,
    condition: 'New',
    badge: 'All-Terrain Twin Motor',
    featured: false,
    rating: 5,
    reviewCount: 38,
    power: 'Electric Remote',
    wheels: '4-wheel',
    batteryRange: '36 hole',
    weightCategory: '10–13 kg',
    weightKg: 13,
    foldSize: 'Compact flat-fold',
    seats: 'Walk-behind / Remote',
    primaryKeyword: 'mgi zip navigator at all terrain buggy',
    shortDescription: 'All-terrain twin calibrated 230W motors, active gyro straight tracking, and full directional remote control.',
    description: 'The MGI Zip Navigator AT All-Terrain model conquers steep undulations and heavy Australian grass with dual independent motors, rear fifth anti-tip wheel, and Gyroscopic Straight Tracker technology that automatically corrects side-slope drift.',
    specs: {
      power: 'Full Directional Ergonomic Remote Handset',
      motor: 'Twin 230W Independent Calibrated Drive Motors',
      battery: '24V 380Wh Click & Go Lithium (36 Hole)',
      weight: '13.0 kg (Without Battery)',
      wheels: 'All-Terrain Dual Front Swivel & Rear Anti-Tip',
      foldSize: '70cm x 47cm x 42cm',
      brakes: 'Downhill Speed Regulation & Electronic Park Brake',
      warranty: '3-Year Australian Factory Warranty'
    },
    images: [
      '/images/products/mgi-zip-navigator-at-all-terrain-golf-buggy/main.webp',
      '/images/products/mgi-zip-navigator-at-all-terrain-golf-buggy/gallery-2.webp',
      '/images/products/mgi-zip-navigator-at-all-terrain-golf-buggy/gallery-3.webp',
      '/images/products/mgi-zip-navigator-at-all-terrain-golf-buggy/gallery-4.webp'
    ]
  },
  {
    slug: 'motocaddy-m5-gps-dhc-electric-golf-buggy',
    name: 'Motocaddy M5 GPS DHC Electric Golf Buggy',
    brand: 'motocaddy',
    brandName: 'Motocaddy',
    category: 'gps-follow-buggies',
    categoryPath: '/electric-golf-buggies/gps-follow/',
    price: 1899,
    condition: 'New',
    badge: 'Built-In Course GPS',
    featured: true,
    rating: 4.9,
    reviewCount: 94,
    power: 'Electric Touchscreen',
    wheels: '3-wheel',
    batteryRange: '36 hole',
    weightCategory: '10–13 kg',
    weightKg: 10.9,
    foldSize: 'Slim-Fold Compact',
    seats: 'Walk-behind',
    primaryKeyword: 'motocaddy m5 gps dhc electric golf buggy',
    shortDescription: 'Responsive 3.5-inch touchscreen GPS preloaded with 40,000+ courses, Downhill Control (DHC), and whisper-quiet 230W motor.',
    description: 'The Motocaddy M5 GPS DHC brings high-accuracy GPS fairway distances right to your buggy handle. Features a 3.5-inch colour touchscreen readable in direct Australian sunlight, automatic downhill speed control, electronic parking brake, and ultra-compact folding frame.',
    specs: {
      power: 'High-Res Touchscreen GPS & Digital Speed Dial',
      motor: '230W Whisper-Quiet DHC Motor System',
      battery: '28.8V High-Capacity Lithium Pack (36 Hole)',
      weight: '10.9 kg (Without Battery)',
      wheels: 'All-Terrain Inverted Wheels with DHC',
      foldSize: '65cm x 47cm x 41cm',
      brakes: 'Automatic Downhill Brake & Electronic Parking Brake',
      warranty: '3-Year Australian Warranty'
    },
    images: [
      '/images/products/motocaddy-m5-gps-dhc-electric-golf-buggy/main.webp',
      '/images/products/motocaddy-m5-gps-dhc-electric-golf-buggy/gallery-2.webp',
      '/images/products/motocaddy-m5-gps-dhc-electric-golf-buggy/gallery-3.webp',
      '/images/products/motocaddy-m5-gps-dhc-electric-golf-buggy/gallery-4.webp',
      '/images/products/motocaddy-m5-gps-dhc-electric-golf-buggy/gallery-5.webp'
    ]
  },
  {
    slug: 'powakaddy-fx7-gps-36-hole-electric-golf-buggy',
    name: 'PowaKaddy FX7 GPS 36-Hole Electric Golf Buggy',
    brand: 'powakaddy',
    brandName: 'PowaKaddy',
    category: 'gps-follow-buggies',
    categoryPath: '/electric-golf-buggies/gps-follow/',
    price: 1799,
    condition: 'New',
    badge: 'Flagship 3.5" Optical GPS',
    featured: false,
    rating: 4.9,
    reviewCount: 82,
    power: 'Electric Touchscreen',
    wheels: '3-wheel',
    batteryRange: '36 hole',
    weightCategory: 'Under 10 kg',
    weightKg: 9.6,
    foldSize: '1-Click Fold',
    seats: 'Walk-behind',
    primaryKeyword: 'powakaddy fx7 gps electric golf buggy',
    shortDescription: 'Cutting-edge 3.5" full colour touchscreen with optical distance measuring, Plug\'n\'Play lithium battery, and ultra-quiet motor.',
    description: 'The PowaKaddy FX7 GPS is the most technologically advanced walk-behind buggy in the FX collection. Featuring a super-responsive 3.5" optical display, fast distance calculations to greens and hazards, and PowaKaddy\'s 1-Click folding system.',
    specs: {
      power: 'Full Colour Touchscreen GPS Interface',
      motor: 'High Power 30V 230W Motor',
      battery: 'Plug\'n\'Play 30V Max Lithium (36 Hole)',
      weight: '9.6 kg',
      wheels: 'Low-Profile Sports Wheels',
      foldSize: '80cm x 56cm x 34cm',
      brakes: 'Electronic Speed Regulation',
      warranty: '3-Year Australian Warranty'
    },
    images: [
      '/images/products/powakaddy-fx7-gps-36-hole-electric-golf-buggy/main.webp',
      '/images/products/powakaddy-fx7-gps-36-hole-electric-golf-buggy/gallery-2.webp',
      '/images/products/powakaddy-fx7-gps-36-hole-electric-golf-buggy/gallery-3.webp'
    ]
  },
  {
    slug: 'stewart-golf-vertx-remote-electric-buggy',
    name: 'Stewart Golf VERTX Remote Electric Golf Buggy',
    brand: 'stewart-golf',
    brandName: 'Stewart Golf',
    category: 'remote-control-golf-buggies',
    categoryPath: '/remote-control-golf-buggies/',
    price: 2699,
    condition: 'New',
    badge: 'Active Terrain Stability',
    featured: true,
    rating: 5,
    reviewCount: 67,
    power: 'Electric Remote',
    wheels: '4-wheel',
    batteryRange: '45 hole',
    weightCategory: '14+ kg',
    weightKg: 14.5,
    foldSize: 'Compact flat-fold',
    seats: 'Remote / Walk-behind',
    primaryKeyword: 'stewart golf vertx remote electric buggy',
    shortDescription: 'British precision engineering featuring Active Terrain Control, 100-metre remote range, and SmartPower lithium battery system.',
    description: 'The Stewart Golf VERTX Remote represents the pinnacle of remote-controlled golf trolleys. Active Terrain Stability constantly calculates pitch and roll to keep the buggy tracking straight across the steepest side slopes and undulating fairways.',
    specs: {
      power: 'Rechargeable Handset with 100m Range',
      motor: 'Twin 230W Calibrated Stealth Drive Motors',
      battery: 'SmartPower Lithium (45 Hole Capacity)',
      weight: '14.5 kg',
      wheels: 'Twin Front Swivel Wheels & Anti-Tip Rear',
      foldSize: '64cm x 55cm x 32cm',
      brakes: 'Active Downhill Dynamic Braking',
      warranty: '3-Year Factory Warranty'
    },
    images: [
      '/images/products/stewart-golf-vertx-remote-electric-buggy/main.webp',
      '/images/products/stewart-golf-vertx-remote-electric-buggy/gallery-2.webp',
      '/images/products/stewart-golf-vertx-remote-electric-buggy/gallery-3.webp',
      '/images/products/stewart-golf-vertx-remote-electric-buggy/gallery-4.webp',
      '/images/products/stewart-golf-vertx-remote-electric-buggy/gallery-5.webp',
      '/images/products/stewart-golf-vertx-remote-electric-buggy/gallery-6.webp',
      '/images/products/stewart-golf-vertx-remote-electric-buggy/gallery-7.webp'
    ]
  },
  {
    slug: 'stewart-golf-x10-follow-electric-buggy',
    name: 'Stewart Golf X10 Follow Autonomous Electric Buggy',
    brand: 'stewart-golf',
    brandName: 'Stewart Golf',
    category: 'gps-follow-buggies',
    categoryPath: '/electric-golf-buggies/gps-follow/',
    price: 3199,
    condition: 'New',
    badge: 'True Autonomous Follow',
    featured: true,
    rating: 5,
    reviewCount: 78,
    power: 'Autonomous Follow & Remote',
    wheels: '4-wheel',
    batteryRange: '36 hole',
    weightCategory: '14+ kg',
    weightKg: 14.8,
    foldSize: 'Compact fold',
    seats: 'Autonomous / Remote',
    primaryKeyword: 'stewart golf x10 follow electric buggy',
    shortDescription: 'Seventh-generation autonomous follow technology that tracks you seamlessly down the fairway without touching a button.',
    description: 'The iconic Stewart Golf X10 Follow uses neural tracking technology to monitor your position and follow you automatically down the fairway. Step forward and it rolls behind; stop and it halts instantly. Includes remote handset for manual guidance.',
    specs: {
      power: 'Seventh-Gen Autonomous Follow System & Remote',
      motor: 'Twin Calibrated 230W Motors',
      battery: 'SmartPower Lithium Pack (36 Hole)',
      weight: '14.8 kg',
      wheels: 'Dual Front Casters with Dual Anti-Tip Rollers',
      foldSize: '65cm x 56cm x 33cm',
      brakes: 'Smart Regenerative Dynamic Braking',
      warranty: '3-Year Australian Warranty'
    },
    images: [
      '/images/products/stewart-golf-x10-follow-electric-buggy/main.webp',
      '/images/products/stewart-golf-x10-follow-electric-buggy/gallery-2.webp',
      '/images/products/stewart-golf-x10-follow-electric-buggy/gallery-3.webp',
      '/images/products/stewart-golf-x10-follow-electric-buggy/gallery-4.webp'
    ]
  },
  {
    slug: 'powakaddy-rx1-gps-remote-electric-golf-buggy',
    name: 'PowaKaddy RX1 GPS Remote Electric Golf Buggy',
    brand: 'powakaddy',
    brandName: 'PowaKaddy',
    category: 'remote-control-golf-buggies',
    categoryPath: '/remote-control-golf-buggies/',
    price: 2499,
    condition: 'New',
    badge: 'Remote + GPS Integrated',
    featured: false,
    rating: 4.9,
    reviewCount: 53,
    power: 'Electric Remote',
    wheels: '4-wheel',
    batteryRange: '36 hole',
    weightCategory: '14+ kg',
    weightKg: 14,
    foldSize: 'Slim fold',
    seats: 'Remote / Walk-behind',
    primaryKeyword: 'powakaddy rx1 gps remote electric golf buggy',
    shortDescription: 'Dual control freedom combining ergonomic remote handset navigation with a 3.5-inch touchscreen course GPS.',
    description: 'The PowaKaddy RX1 GPS Remote combines high-performance wireless handset steering with an ultra-bright 3.5" GPS touchscreen on the handle. Dual 230W motors power through deep rough and steep climbs while twin rear anti-tip wheels guarantee rock-solid stability.',
    specs: {
      power: 'Ergonomic Remote Control & 3.5" Touchscreen GPS',
      motor: 'Twin 30V 230W Motors',
      battery: 'Plug\'n\'Play 30V High-Capacity Lithium',
      weight: '14.0 kg',
      wheels: 'All-Terrain Sports Wheels with Anti-Tip',
      foldSize: '80cm x 56cm x 34cm',
      brakes: 'Electronic Slope Descent Control',
      warranty: '3-Year Australian Warranty'
    },
    images: [
      '/images/products/powakaddy-rx1-gps-remote-electric-golf-buggy/main.webp',
      '/images/products/powakaddy-rx1-gps-remote-electric-golf-buggy/gallery-2.webp',
      '/images/products/powakaddy-rx1-gps-remote-electric-golf-buggy/gallery-3.webp',
      '/images/products/powakaddy-rx1-gps-remote-electric-golf-buggy/gallery-4.webp'
    ]
  },
  {
    slug: 'powakaddy-dlx-push-button-electric-golf-buggy',
    name: 'PowaKaddy DLX Electric Golf Buggy',
    brand: 'powakaddy',
    brandName: 'PowaKaddy',
    category: 'electric-golf-buggies',
    categoryPath: '/electric-golf-buggies/walk-behind/',
    price: 1199,
    condition: 'New',
    badge: 'Push-Button Benchmark',
    featured: false,
    rating: 4.8,
    reviewCount: 65,
    power: 'Electric',
    wheels: '3-wheel',
    batteryRange: '36 hole',
    weightCategory: 'Under 10 kg',
    weightKg: 9.4,
    foldSize: '1-Click Fold',
    seats: 'Walk-behind',
    primaryKeyword: 'powakaddy dlx electric golf buggy',
    shortDescription: 'Reliable, lightweight push-button electric buggy with whisper-quiet motor and high-performance lithium power.',
    description: 'The PowaKaddy DLX delivers proven British engineering in a simple, durable walk-behind design. Turn the ergonomic speed dial, press start, and enjoy effortless power across 36 holes on a single charge.',
    specs: {
      power: 'Push-Button Variable Digital Speed Dial',
      motor: '230W Whisper-Quiet Motor',
      battery: 'Plug\'n\'Play Lightweight Lithium (36 Hole)',
      weight: '9.4 kg',
      wheels: 'Low-Profile Quick-Release Wheels',
      foldSize: '78cm x 54cm x 35cm',
      brakes: 'Dynamic Speed Descent Brakes',
      warranty: '3-Year Australian Warranty'
    },
    images: [
      '/images/products/powakaddy-dlx-push-button-electric-golf-buggy/main.webp',
      '/images/products/powakaddy-dlx-push-button-electric-golf-buggy/gallery-2.webp',
      '/images/products/powakaddy-dlx-push-button-electric-golf-buggy/gallery-3.webp'
    ]
  },
  {
    slug: 'big-max-iq-2-360-push-golf-buggy',
    name: 'Big Max IQ 2 360 Push Golf Buggy',
    brand: 'big-max',
    brandName: 'Big Max',
    category: 'push-pull-golf-buggies',
    categoryPath: '/push-pull-golf-buggies/',
    price: 499,
    condition: 'New',
    badge: '360° Front Swivel',
    featured: false,
    rating: 4.9,
    reviewCount: 71,
    power: 'Manual Push',
    wheels: '3-wheel',
    batteryRange: 'N/A - Push',
    weightCategory: 'Under 7 kg',
    weightKg: 6.8,
    foldSize: 'Ultra-compact cubic fold',
    seats: 'Manual push',
    primaryKeyword: 'big max iq 2 360 push golf buggy',
    shortDescription: 'Full 360-degree front wheel spin for effortless fairway turning, deluxe organiser panel, and ultra-compact cubic fold.',
    description: 'The Big Max IQ 2 360 turns on a dime with its lockable 360-degree front wheel. Folds down into a compact cubic shape that fits in any Australian car boot alongside a full tour bag.',
    specs: {
      power: 'Manual Push with 360° Front Swivel Wheel',
      motor: 'None (Manual Ultra-Lightweight)',
      battery: 'None',
      weight: '6.8 kg',
      wheels: '360° Front Swivel + 2 Large Sealed Ball-Bearing Rear',
      foldSize: '58cm x 37cm x 42cm',
      brakes: 'Hand-Operated Foot Brake',
      warranty: '5-Year Manufacturer Warranty'
    },
    images: [
      '/images/products/big-max-iq-2-360-push-golf-buggy/main.webp',
      '/images/products/big-max-iq-2-360-push-golf-buggy/gallery-2.webp',
      '/images/products/big-max-iq-2-360-push-golf-buggy/gallery-3.webp',
      '/images/products/big-max-iq-2-360-push-golf-buggy/gallery-4.webp',
      '/images/products/big-max-iq-2-360-push-golf-buggy/gallery-5.webp'
    ]
  }
];

export function getProductBySlug(slug) {
  return PRODUCTS.find((p) => p.slug === slug);
}

export function getProductsByCategory(categorySlug) {
  return PRODUCTS.filter((p) => p.category === categorySlug);
}

export function getProductsByBrand(brandSlug) {
  return PRODUCTS.filter((p) => p.brand === brandSlug);
}

export function getFeaturedProducts() {
  return PRODUCTS.filter((p) => p.featured);
}
