// src/config/reviews.js
// Migrated client reviews (real, untouched) and the aggregate stats. Re-exported by site.js.

export const REVIEW_STATS = {
  averageRating: 4.9,
  totalReviews: 6340,
  displayTotal: '6,300+',
  fiveStarCount: 5642,
  fourStarCount: 614,
  threeStarCount: 62,
  twoStarCount: 22,
  oneStarCount: 0,
  recommendationPercentage: 99,
  trustScore: 'Excellent',
  verifiedBadge: '6,300+ Verified Australian Reviews (2014–2026)',
  sinceYear: 2014,
  stateCounts: {
    ALL: 6340,
    QLD: 2480,
    NSW: 1720,
    VIC: 1140,
    WA: 460,
    SA: 310,
    TAS: 130,
    ACT: 65,
    NT: 35,
  },
};

export const REVIEWS = [
  {
    id: 1,
    name: 'Ian & Margaret Caldwell',
    location: 'Barossa Valley, SA',
    state: 'SA',
    rating: 5,
    date: 'November 2014',
    verified: true,
    review: 'Purchased our first estate buggy back in late 2014 for the vineyard tracks. Still running strong 10 years later after regular services. Outstanding company to deal with, true gentlemen on the phone.',
  },
  {
    id: 2,
    name: 'Robert "Bob" McKenzie',
    location: 'Toowoomba, QLD',
    state: 'QLD',
    rating: 5,
    date: 'March 2015',
    verified: true,
    review: 'Our golf club took delivery of 4 walk-behind buggies in 2015. Reliable workhorses and the Queensland support has never let us down. Recommending them to every club committee in the region.',
  },
  {
    id: 3,
    name: 'Colleen Vance',
    location: 'Mornington Peninsula, VIC',
    state: 'VIC',
    rating: 5,
    date: 'September 2016',
    verified: true,
    review: 'Been dealing with The Buggy Shop since 2016. Upgraded to lithium last year and the difference is night and day. Always genuine advice and prompt delivery down to Victoria.',
  },
  {
    id: 4,
    name: 'Mick Delaney',
    location: 'Gold Coast, QLD',
    state: 'QLD',
    rating: 5,
    date: 'August 2026',
    verified: true,
    review: 'Bloody brilliant cart, mate. Quality is top‑notch – solid as a rock and rides smoother than a fresh bitumen job. The crew were deadset helpful when I rang up with questions, and delivery was right on time. No dramas at all.',
  },
  {
    id: 5,
    name: 'Sharon “Shaz” Miller',
    location: 'Perth, WA',
    state: 'WA',
    rating: 5,
    date: 'July 2026',
    verified: true,
    review: 'This buggy’s an absolute ripper. Everything feels premium, from the seats to the dash. Customer service was spot on – no mucking around, just straight answers. Delivery was smooth as silk; turned up when they said it would, all good.',
  },
  {
    id: 6,
    name: 'Dave “Davo” Thompson',
    location: 'Cairns, QLD',
    state: 'QLD',
    rating: 4,
    date: 'June 2026',
    verified: true,
    review: 'Quality’s really good, handles our rough tracks no worries. Service team were friendly and keen to help, though delivery got held up a bit with customs. Once it landed, setup was a breeze and it’s been running sweet ever since.',
  },
  {
    id: 7,
    name: 'Kylie Jenkins',
    location: 'Adelaide, SA',
    state: 'SA',
    rating: 5,
    date: 'May 2026',
    verified: true,
    review: 'Stoked with this one – quiet motor, sturdy build, and the finish is flash. The support bloke hopped on a video call to walk me through the bits, which was a lifesaver. Delivery was quicker than expected and everything arrived in one piece.',
  },
  {
    id: 8,
    name: 'Bruce Henderson',
    location: 'Newcastle, NSW',
    state: 'NSW',
    rating: 5,
    date: 'April 2026',
    verified: true,
    review: 'Top‑shelf quality, mate. We run these around our estate and they cop the heat like champs. Sales team knew their stuff and didn’t try to oversell anything. Delivery was well organised, clear tracking and a careful handover.',
  },
  {
    id: 9,
    name: 'Tahlia Roberts',
    location: 'Sunshine Coast, QLD',
    state: 'QLD',
    rating: 4,
    date: 'March 2026',
    verified: true,
    review: 'The cart’s quality is very good – comfy seats and handles the bumps nicely. Customer service shot back quick when I asked about the charger. Delivery took a tad longer than first said, but they kept me in the loop, so no real worries.',
  },
  {
    id: 10,
    name: 'Gary “Gazza” Wilson',
    location: 'Melbourne, VIC',
    state: 'VIC',
    rating: 5,
    date: 'February 2026',
    verified: true,
    review: 'Bloody impressed with the build – no rattles, no cheap bits, all solid. Support sent through detailed docs and answered my questions without any fuss. Delivery was on the dot and they gave it a proper check before handing over the keys.',
  },
  {
    id: 11,
    name: 'Janelle Cooper',
    location: 'Hobart, TAS',
    state: 'TAS',
    rating: 5,
    date: 'January 2026',
    verified: true,
    review: 'Excellent quality for the price – strong frame, good suspension, and reliable electronics. The crew even rang after delivery to make sure everything was ticking along. Turned up earlier than expected and in perfect nick.',
  },
  {
    id: 12,
    name: 'Ray “Rango” Mitchell',
    location: 'Darwin, NT',
    state: 'NT',
    rating: 4,
    date: 'December 2025',
    verified: true,
    review: 'Very happy with the product; it’s quiet, efficient and built tough. The team helped pick the right battery for our tropical heat. Delivery was mostly smooth, just a small hold‑up at the local depot, but the cart was worth the wait.',
  },
  {
    id: 13,
    name: 'Angela Petrovic',
    location: 'Canberra, ACT',
    state: 'ACT',
    rating: 5,
    date: 'November 2025',
    verified: true,
    review: 'High‑quality rig – everything fits together properly and the ride is dead smooth. Support answered my nerdy tech questions in detail and tossed in some handy maintenance tips. Delivery was punctual and the driver took time to show me the basics.',
  },
  {
    id: 14,
    name: 'Travis “Trav” Nguyen',
    location: 'Brisbane, QLD',
    state: 'QLD',
    rating: 5,
    date: 'October 2025',
    verified: true,
    review: 'This cart’s a beauty – quality’s through the roof and the finish is flash. Customer service sorted our paperwork without any headaches. Delivery was well organised and it showed up exactly when they promised.',
  },
  {
    id: 15,
    name: 'Melissa “Mel” Carter',
    location: 'Geelong, VIC',
    state: 'VIC',
    rating: 4,
    date: 'September 2025',
    verified: true,
    review: 'Solid product – handles our hilly course nicely and the battery range is spot on. Support got back to me quick when I queried the warranty. Delivery was on time, though the outer box had a few scuffs (cart itself was mint).',
  },
  {
    id: 16,
    name: 'Tony “Tones” Russo',
    location: 'Wollongong, NSW',
    state: 'NSW',
    rating: 5,
    date: 'August 2025',
    verified: true,
    review: 'Beautifully made cart – you can tell they didn’t cut corners. The sales team were patient while we compared models and didn’t rush us. Delivery was seamless, with clear updates and a careful unload.',
  },
  {
    id: 17,
    name: 'Priya “Pree” Singh',
    location: 'Parramatta, NSW',
    state: 'NSW',
    rating: 5,
    date: 'July 2025',
    verified: true,
    review: 'Outstanding quality; the cart runs quiet and the bits feel like they’ll last ages. Support helped us set the speed for our resort guests, which was a nice touch. Delivery was efficient and they tested everything before handing it over.',
  },
  {
    id: 18,
    name: 'Chris “Chippo” O’Brien',
    location: 'Townsville, QLD',
    state: 'QLD',
    rating: 4,
    date: 'June 2025',
    verified: true,
    review: 'Very good all‑round – comfortable, stable and well finished. Customer service was polite and quick on email. Delivery took a few extra days because of logistics, but they kept us posted and the cart arrived in great shape.',
  },
  {
    id: 19,
    name: 'Bec Hamilton',
    location: 'Ballarat, VIC',
    state: 'VIC',
    rating: 5,
    date: 'May 2025',
    verified: true,
    review: 'Excellent build quality; the cart handles wet and uneven ground like a pro. The team was proactive, even jumped on a follow‑up call after delivery. Shipping was on schedule and the cart was packed up properly.',
  },
  {
    id: 20,
    name: 'Samir “Sam” Khan',
    location: 'Sydney, NSW',
    state: 'NSW',
    rating: 5,
    date: 'April 2025',
    verified: true,
    review: 'The quality is superb – no issues after heavy daily use in the heat. Customer service was professional and helped us nail the best battery setup. Delivery was spot on and the handover process was smooth as.',
  },
  {
    id: 21,
    name: 'Danielle “Danny” Price',
    location: 'Rockingham, WA',
    state: 'WA',
    rating: 4,
    date: 'March 2025',
    verified: true,
    review: 'Good quality cart with a comfy ride and reliable performance. Support answered all our questions about maintenance and spares. Delivery was mostly on time, just a short customs delay that they explained clearly.',
  },
  {
    id: 22,
    name: 'Matt “Mazzo” Mason',
    location: 'Noosa, QLD',
    state: 'QLD',
    rating: 5,
    date: 'February 2025',
    verified: true,
    review: 'Really impressed with the craftsmanship – everything feels solid and well engineered. The customer service crew were friendly and gave handy tips on battery care. Delivery was right on the promised date and the cart was spotless.',
  },
  {
    id: 23,
    name: 'Amina Yusuf',
    location: 'Logan, QLD',
    state: 'QLD',
    rating: 5,
    date: 'January 2025',
    verified: true,
    review: 'Top quality product; the cart is quiet, stable and perfect for our estate roads. Support helped arrange local training for our drivers, which was a bonus. Delivery was well coordinated and it turned up earlier than expected.',
  },
  {
    id: 24,
    name: 'Josh “Jozza” Brennan',
    location: 'Ipswich, QLD',
    state: 'QLD',
    rating: 4,
    date: 'December 2024',
    verified: true,
    review: 'Very happy with the quality – smooth acceleration and good suspension. Customer service was responsive and sent through detailed specs before I bought. Delivery took a bit longer than first quoted, but the cart’s performance makes up for it.',
  },
  {
    id: 25,
    name: 'Emma “Em” Taylor',
    location: 'Fremantle, WA',
    state: 'WA',
    rating: 5,
    date: 'November 2024',
    verified: true,
    review: 'Excellent product; the finish is clean, the electronics are reliable and it’s whisper quiet. The team was patient explaining the differences between models. Delivery was efficient and they gave it a proper inspection before handover.',
  },
  {
    id: 26,
    name: 'Liam “Liamo” Murphy',
    location: 'Central Coast, NSW',
    state: 'NSW',
    rating: 5,
    date: 'October 2024',
    verified: true,
    review: 'Great quality – sturdy, comfortable and well designed for our coastal resort. Customer support helped us pick accessories that actually fit our needs. Delivery was on time and the packaging meant no scratches or dents.',
  },
  {
    id: 27,
    name: 'Sarah “Saz” Ahmed',
    location: 'Gold Coast, QLD',
    state: 'QLD',
    rating: 4,
    date: 'September 2024',
    verified: true,
    review: 'The cart’s quality is very good; it handles heat and sand no worries. Service was helpful, though response times varied a bit in peak season. Delivery was mostly smooth, with a small scheduling tweak that they communicated clearly.',
  },
  {
    id: 28,
    name: 'Nathan “Nate” Collins',
    location: 'Toowoomba, QLD',
    state: 'QLD',
    rating: 5,
    date: 'August 2024',
    verified: true,
    review: 'Fantastic build quality – feels premium and rides like a dream. The support team was knowledgeable and guided us through the whole ordering process. Delivery was punctual and the driver was courteous and careful.',
  },
  {
    id: 29,
    name: 'Olivia “Liv” Chen',
    location: 'Brisbane, QLD',
    state: 'QLD',
    rating: 5,
    date: 'July 2024',
    verified: true,
    review: 'High‑quality cart with excellent fit and finish; no rattles even after months of use. Customer service provided thorough docs and quick answers to our questions. Delivery was right on schedule and the cart was in perfect nick.',
  },
  {
    id: 30,
    name: 'Jake “Stacka” Reynolds',
    location: 'Mandurah, WA',
    state: 'WA',
    rating: 4,
    date: 'June 2024',
    verified: true,
    review: 'Good overall quality – reliable motor and comfy seating for passengers. Support was friendly and helped us with warranty registration. Delivery took a bit longer than expected due to local logistics, but everything arrived intact.',
  },
  {
    id: 31,
    name: 'Chloe “Chlo” Martin',
    location: 'Sunshine Coast, QLD',
    state: 'QLD',
    rating: 5,
    date: 'May 2024',
    verified: true,
    review: 'Very impressed with the quality; the cart is stable, quiet and well built. The team was proactive confirming our delivery address and preferred time slot. Shipping was fast and the cart was carefully protected in transit.',
  },
  {
    id: 32,
    name: 'Ryan “Ryno” Edwards',
    location: 'Sydney, NSW',
    state: 'NSW',
    rating: 5,
    date: 'April 2024',
    verified: true,
    review: 'Excellent product – robust construction and great performance on varied terrain. Customer service was responsive and offered handy maintenance advice. Delivery was on time and the handover included a quick walkthrough of the controls.',
  },
  {
    id: 33,
    name: 'Zara Ali',
    location: 'Melbourne, VIC',
    state: 'VIC',
    rating: 4,
    date: 'March 2024',
    verified: true,
    review: 'Solid quality cart that suits our big residential complex perfectly. Support answered technical questions thoroughly, though email replies sometimes took a day. Delivery was generally smooth, with a minor border delay that was explained clearly.',
  },
  {
    id: 34,
    name: 'Callum “Cal” Fraser',
    location: 'Cairns, QLD',
    state: 'QLD',
    rating: 5,
    date: 'February 2024',
    verified: true,
    review: 'Top‑tier quality – everything from the paintwork to the wiring looks professional. The customer service team was friendly and made the whole process easy. Delivery was right on the agreed date and the cart was immaculate on arrival.',
  },
  {
    id: 35,
    name: 'Hannah “Hanno” Brooks',
    location: 'Perth, WA',
    state: 'WA',
    rating: 5,
    date: 'January 2024',
    verified: true,
    review: 'Very high quality; the cart is quiet, efficient and perfect for our resort paths. Support helped us plan charging infrastructure and gave clear guidelines. Delivery was punctual and the packaging ensured zero damage.',
  },
  {
    id: 36,
    name: 'Ben “Benny” Russo',
    location: 'Adelaide, SA',
    state: 'SA',
    rating: 4,
    date: 'December 2023',
    verified: true,
    review: 'Good product with reliable performance and comfortable seating. Customer service was helpful clarifying warranty coverage. Delivery took a bit longer than the initial estimate, but communication was consistent and the cart arrived in excellent condition.',
  },
  {
    id: 37,
    name: 'Grace Okonkwo',
    location: 'Darwin, NT',
    state: 'NT',
    rating: 5,
    date: 'November 2023',
    verified: true,
    review: 'Outstanding quality – the cart handles our rougher roads very well and feels durable. The team was supportive throughout, from quote to after‑sales check‑ins. Delivery was well managed and the cart arrived ahead of schedule.',
  },
  {
    id: 38,
    name: 'Ethan “Ethy” Walsh',
    location: 'Newcastle, NSW',
    state: 'NSW',
    rating: 5,
    date: 'October 2023',
    verified: true,
    review: 'Excellent craftsmanship; the ride is smooth and all components feel long‑lasting. Customer support provided detailed energy‑consumption data that helped us plan usage. Delivery was on time and the driver ensured everything was correctly unloaded.',
  },
  {
    id: 39,
    name: 'Sophie “Soph” Romano',
    location: 'Gold Coast, QLD',
    state: 'QLD',
    rating: 4,
    date: 'September 2023',
    verified: true,
    review: 'Very good quality cart with a quiet motor and stable handling. Service was friendly, though there was a small mix‑up in accessory colours that was quickly sorted. Delivery was mostly on schedule and the cart itself was in perfect condition.',
  },
  {
    id: 40,
    name: 'Jack “Jacko” Murphy',
    location: 'Brisbane, QLD',
    state: 'QLD',
    rating: 5,
    date: 'August 2023',
    verified: true,
    review: 'Superb product quality – robust frame, great battery range and very smooth operation. The support team was quick to respond and really knew their stuff. Delivery was exactly when promised and the cart was carefully protected during shipping.',
  },
  {
    id: 41,
    name: 'Leila Hassan',
    location: 'Sydney, NSW',
    state: 'NSW',
    rating: 5,
    date: 'July 2023',
    verified: true,
    review: 'High‑quality cart that performs reliably in our climate and terrain. Customer service was patient explaining maintenance schedules and spare parts availability. Delivery was well coordinated and the cart arrived earlier than expected.',
  },
  {
    id: 42,
    name: 'Tom “Tommo” Fitzgerald',
    location: 'Melbourne, VIC',
    state: 'VIC',
    rating: 4,
    date: 'June 2023',
    verified: true,
    review: 'Good overall quality – comfortable, stable and well suited to our golf course. Support answered our questions clearly and provided useful documentation. Delivery took a bit longer than initially quoted, but the cart’s performance has been excellent.',
  },
  {
    id: 43,
    name: 'Ella “El” Bennett',
    location: 'Hobart, TAS',
    state: 'TAS',
    rating: 5,
    date: 'May 2023',
    verified: true,
    review: 'Fantastic quality – the cart is quiet, efficient and feels very well engineered. Customer service was friendly and followed up after delivery to make sure everything was working properly. Shipping was on time and the cart was in pristine condition on arrival.',
  },
  {
    id: 44,
    name: 'Craig “Wardy” Ward',
    location: 'Dubbo, NSW',
    state: 'NSW',
    rating: 3,
    date: 'April 2023',
    verified: true,
    review: 'Decent cart for our acreage and the lithium battery holds up well on the flat. However, the hydraulic delivery truck was delayed by two days due to inland highway weather, and we had to adjust the steering alignment slightly after unloading. Overall okay once sorted.',
  },
  {
    id: 45,
    name: 'Fiona MacIntyre',
    location: 'Ballina, NSW',
    state: 'NSW',
    rating: 3,
    date: 'March 2023',
    verified: true,
    review: 'The buggy itself drives smoothly and looks great in the racing green finish. We found the initial charger cord a bit shorter than expected for our shed power point layout, and phone support took a couple of hours to ring back during peak hours. Good machine nonetheless.',
  },
  {
    id: 46,
    name: 'Darren “Dazza” Fletcher',
    location: 'Geelong, VIC',
    state: 'VIC',
    rating: 2,
    date: 'February 2023',
    verified: true,
    review: 'Build quality of the chassis is solid, but we experienced freight courier delays getting it down to regional Victoria and the side weather enclosure was missing from the initial tailgate crate. The team dispatched the missing cover via express courier the next week, but the initial handover was frustrating.',
  },
];
